<?php

use Illuminate\Database\Seeder;

class AgreementPriceBreakSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $collection = array(['agreementID'=>1, 'revision'=>1, 'itemID'=>23, 'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>23, 'priceBreak'=>100, 'discount'=>'0.95'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>23, 'priceBreak'=>1000,'discount'=> '0.90'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>23, 'priceBreak'=>10000, 'discount'=>'0.85'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>43, 'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>118,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>118,'priceBreak'=> 100, 'discount'=>'0.95'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>118,'priceBreak'=> 1000,'discount'=> '0.90'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>118,'priceBreak'=> 10000, 'discount'=>'0.85'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>176,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>257,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>286,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>323,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>325,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>366,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>1, 'revision'=>1, 'itemID'=>444,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>4,  'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>32, 'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>43, 'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>79, 'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>85, 'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>240,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>240,'priceBreak'=> 100, 'discount'=>'0.95'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>240,'priceBreak'=> 1000,'discount'=> '0.90'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>240,'priceBreak'=> 10000, 'discount'=>'0.85'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>248,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>312,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>382,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>510,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>510,'priceBreak'=> 100, 'discount'=>'0.95'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>510,'priceBreak'=> 1000,'discount'=> '0.90'],
							['agreementID'=>2, 'revision'=>1, 'itemID'=>510,'priceBreak'=> 10000,'discount'=> '0.85'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>13, 'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>162,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>202,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>209,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>212,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>225,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>225,'priceBreak'=> 100, 'discount'=>'0.95'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>225,'priceBreak'=> 1000,'discount'=> '0.90'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>225,'priceBreak'=> 10000, 'discount'=>'0.85'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>227,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>313,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>318,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>3, 'revision'=>1, 'itemID'=>452,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>46, 'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>77, 'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>186,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>186,'priceBreak'=>100, 'discount'=>'0.95'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>186,'priceBreak'=>1000, 'discount'=>'0.90'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>186,'priceBreak'=>10000,'discount'=> '0.85'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>234,'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>237,'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>237,'priceBreak'=>100, 'discount'=>'0.95'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>237,'priceBreak'=>1000,'discount'=> '0.90'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>237,'priceBreak'=>10000, 'discount'=>'0.85'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>293,'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>329,'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>427,'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>435,'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>4, 'revision'=>1, 'itemID'=>508,'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>28, 'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>98, 'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>174,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>174,'priceBreak'=> 100, 'discount'=>'0.95'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>174,'priceBreak'=> 1000, 'discount'=>'0.90'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>174,'priceBreak'=> 10000, 'discount'=>'0.85'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>255,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>307,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>310,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>342,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>386,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>429,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>5, 'revision'=>1, 'itemID'=>484,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>24, 'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>36, 'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>160,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>179,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>210,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>348,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>348,'priceBreak'=> 100, 'discount'=>'0.95'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>348,'priceBreak'=> 1000,'discount'=> '0.90'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>348,'priceBreak'=> 10000, 'discount'=>'0.85'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>423,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>484,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>489,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>6, 'revision'=>1, 'itemID'=>505,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>53, 'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>95, 'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>118,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>182,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>182,'priceBreak'=> 100, 'discount'=>'0.95'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>182,'priceBreak'=> 1000,'discount'=> '0.90'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>182,'priceBreak'=> 10000, 'discount'=>'0.85'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>236,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>260,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>273,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>341,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>409,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>7, 'revision'=>1, 'itemID'=>515,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>4,  'priceBreak'=>0, 'discount'=>'1.00'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>79, 'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>226,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>226,'priceBreak'=> 100, 'discount'=>'0.95'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>226,'priceBreak'=> 1000,'discount'=> '0.90'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>226,'priceBreak'=> 10000, 'discount'=>'0.85'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>236,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>280,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>355,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>389,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>389,'priceBreak'=> 100, 'discount'=>'0.95'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>389,'priceBreak'=> 1000,'discount'=> '0.90'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>389,'priceBreak'=> 10000, 'discount'=>'0.85'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>397,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>451,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>8, 'revision'=>1, 'itemID'=>493,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>2,  'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>118,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>155,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>156,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>239,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>271,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>278,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>278,'priceBreak'=> 100, 'discount'=>'0.95'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>278,'priceBreak'=> 1000,'discount'=> '0.90'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>278,'priceBreak'=> 10000, 'discount'=>'0.85'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>304,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>342,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>9, 'revision'=>1, 'itemID'=>343,'priceBreak'=> 0, 'discount'=>'1.00'],
							['agreementID'=>10,'revision'=>1,'itemID'=> 215,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>11,'revision'=>1,'itemID'=> 522,'priceBreak'=> 0,'discount'=> '1.00'],
							['agreementID'=>12,'revision'=>1,'itemID'=> 522,'priceBreak'=> 0,'discount'=> '1.00'],
						);

		for($i=0; $i<count($collection); $i++) {
			//for debug input data error
			//print_r(Arr::get($collection,$i));
			DB::table('agreement_price_break')->insert([Arr::get($collection,$i)]);
		}
    }
}
