<?php

use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		$collection = array(['itemID'=>1,  'virtualItemID'=>'PAPL-00001', 'categoryID'=>13,'name'=>'21 cm Paper Plate', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>2,  'virtualItemID'=>'PAPL-00002', 'categoryID'=>13,'name'=> '23 cm Solid Paper Plates', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>3,  'virtualItemID'=>'PAPL-00003', 'categoryID'=>13,'name'=> '18 cm Paper Plates', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>4,  'virtualItemID'=>'PLPL-00001', 'categoryID'=>14,'name'=> '7 inch Plastic Plates - Clear', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>5,  'virtualItemID'=>'PLPL-00002', 'categoryID'=>14,'name'=> '7 inch Plastic Plates - Colours', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>6,  'virtualItemID'=>'PLPL-00003', 'categoryID'=>14,'name'=> '9 inch Plastic Plates - Clear', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>7,  'virtualItemID'=>'PLPL-00004', 'categoryID'=>14,'name'=> '9 inch Plastic Plates - Colours', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>8,  'virtualItemID'=>'PAPL-00004', 'categoryID'=>13,'name'=> '18 cm Paper Shell Plate', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>9,  'virtualItemID'=>'PAPL-00005', 'categoryID'=>13,'name'=> '18 cm Paper Shell Plate', 'unitOfMeasurement'=>'25 PCS', 'description'=>''],
							['itemID'=>10, 'virtualItemID'=>'FK-00001',   'categoryID'=>5, 'name'=>'Rococo Cutlery Fork', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>11, 'virtualItemID'=>'FK-00002',   'categoryID'=>5, 'name'=>'Plastic Forks', 'unitOfMeasurement'=>'24 PCS', 'description'=>''],
							['itemID'=>12, 'virtualItemID'=>'FK-00003',   'categoryID'=>5, 'name'=>'SW Plastic Forks - Clear', 'unitOfMeasurement'=>'24 PCS', 'description'=>''],
							['itemID'=>13, 'virtualItemID'=>'KE-00001',   'categoryID'=>6, 'name'=>'Rococo Cutlery Knife', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>14, 'virtualItemID'=>'PACP-00001', 'categoryID'=>15,'name'=> 'Heat Barrier Paper Cups - White', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>15, 'virtualItemID'=>'PLCP-00001', 'categoryID'=>16,'name'=> 'White Plastic Cups', 'unitOfMeasurement'=>'20 PCS', 'description'=>''],
							['itemID'=>16, 'virtualItemID'=>'PACP-00002', 'categoryID'=>15,'name'=> 'Paper Hot Cups with Handles', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>17, 'virtualItemID'=>'PLCP-00002', 'categoryID'=>16,'name'=> 'Plastic Cup - Clear', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>18, 'virtualItemID'=>'PLCP-00003', 'categoryID'=>16,'name'=> 'Plastic Cup - Assorted Colour', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>19, 'virtualItemID'=>'OTHBL-00001','categoryID'=>19,'name'=> 'Party Bowl [Small]', 'unitOfMeasurement'=>'1 PCS', 'description'=>''],
							['itemID'=>20, 'virtualItemID'=>'PABL-00001', 'categoryID'=>17,'name'=> '6 inch Round Paper Bowl', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>21, 'virtualItemID'=>'PLBL-00001', 'categoryID'=>18,'name'=> 'Plastic Bowl - Clear', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>22, 'virtualItemID'=>'PABL-00002', 'categoryID'=>17,'name'=> '22 cm Solid Paper Bowls', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>23, 'virtualItemID'=>'PABL-00003', 'categoryID'=>17,'name'=> '22 cm Solid Paper Bowls', 'unitOfMeasurement'=>'20 PCS', 'description'=>''],
							['itemID'=>24, 'virtualItemID'=>'OTHBL-00002','categoryID'=>19,'name'=> 'Mozaik Pulp Round Bowl 15 cm', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>25, 'virtualItemID'=>'PABL-00004', 'categoryID'=>17,'name'=> '24 cm Gold Royal Shape Paper Bowls', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>26, 'virtualItemID'=>'PABL-00005', 'categoryID'=>17,'name'=> '24 cm Paper Bowls', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>27, 'virtualItemID'=>'PABL-00006', 'categoryID'=>17,'name'=> '24 cm Paper Spaghetti Bowls', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>28, 'virtualItemID'=>'PLBL-00002', 'categoryID'=>18,'name'=> 'Plastic Bowl - Assorted Colours', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>29, 'virtualItemID'=>'PLSP-00001', 'categoryID'=>20,'name'=> 'Plastic Spoons', 'unitOfMeasurement'=>'24 PCS', 'description'=>''],
							['itemID'=>30, 'virtualItemID'=>'PLSP-00002', 'categoryID'=>20,'name'=> '5 inch Plastic Soup Spoons', 'unitOfMeasurement'=>'24 PCS', 'description'=>''],
							['itemID'=>31, 'virtualItemID'=>'PLSP-00003', 'categoryID'=>20,'name'=> 'SW Plastic Spoons - Clear', 'unitOfMeasurement'=>'24 PCS', 'description'=>''],
							['itemID'=>32, 'virtualItemID'=>'PLSP-00004', 'categoryID'=>20,'name'=> 'SW Plastic Spoons - Colours', 'unitOfMeasurement'=>'24 PCS', 'description'=>''],
							['itemID'=>33, 'virtualItemID'=>'OTHSP-00001','categoryID'=>21,'name'=> 'Rococo Cutlery Spoons', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>34, 'virtualItemID'=>'OTHSP-00002','categoryID'=>21,'name'=> 'Rococo Cutlery Spoons', 'unitOfMeasurement'=>'20 PCS', 'description'=>''],
							['itemID'=>35, 'virtualItemID'=>'TP-00001',   'categoryID'=>10,'name'=> 'Wooden Toothpicks', 'unitOfMeasurement'=>'600 PCS', 'description'=>''],
							['itemID'=>36, 'virtualItemID'=>'TP-00002',   'categoryID'=>10,'name'=> 'Wooden Toothpicks', 'unitOfMeasurement'=>'1000 PCS', 'description'=>''],
							['itemID'=>37, 'virtualItemID'=>'CD-00001',   'categoryID'=>11,'name'=> 'Candle 7 inch','unitOfMeasurement'=> '4 PCS', 'description'=>''],
							['itemID'=>38, 'virtualItemID'=>'CD-00002',   'categoryID'=>11,'name'=> 'Party Candle', 'unitOfMeasurement'=>'24 PCS', 'description'=>''],
							['itemID'=>39, 'virtualItemID'=>'CD-00003',   'categoryID'=>11,'name'=> 'Tealight Candles', 'unitOfMeasurement'=>'50 PCS', 'description'=>''],
							['itemID'=>40, 'virtualItemID'=>'TC-00001',   'categoryID'=>12,'name'=> 'Tablecloth 51x51 inch', 'unitOfMeasurement'=>'50 PCS', 'description'=>''],
							['itemID'=>41, 'virtualItemID'=>'TC-00002',   'categoryID'=>12,'name'=> 'Tablecloth 42x42 inch', 'unitOfMeasurement'=>'50 PCS', 'description'=>''],
							['itemID'=>42, 'virtualItemID'=>'TC-00003',   'categoryID'=>12,'name'=> 'Plastic Table Cloth 1.4x2.4m', 'unitOfMeasurement'=>'1 PCS', 'description'=>''],
							['itemID'=>43, 'virtualItemID'=>'CFS-00001',  'categoryID'=>26,'name'=> 'Pink Salmon', 'unitOfMeasurement'=>'210 G', 'description'=>''],
							['itemID'=>44, 'virtualItemID'=>'CFS-00002',  'categoryID'=>26,'name'=> 'Tuna Tempter Lemon Cracked Pepper', 'unitOfMeasurement'=>'95 G', 'description'=>''],
							['itemID'=>45, 'virtualItemID'=>'CFS-00003',  'categoryID'=>26,'name'=> 'Tuna Tempter Chili', 'unitOfMeasurement'=>'95 G', 'description'=>''],
							['itemID'=>46, 'virtualItemID'=>'CFS-00004',  'categoryID'=>26,'name'=> 'Tuna Tempter with Olive Oil', 'unitOfMeasurement'=>'95 G', 'description'=>''],
							['itemID'=>47, 'virtualItemID'=>'CFS-00005',  'categoryID'=>26,'name'=> 'Tuna Tempter Light Sandwich in Springwater', 'unitOfMeasurement'=>'95 G', 'description'=>''],
							['itemID'=>48, 'virtualItemID'=>'CFS-00006',  'categoryID'=>26,'name'=> 'ND Tuna Steak in Sunflower Oil', 'unitOfMeasurement'=>'110 G', 'description'=>''],
							['itemID'=>49, 'virtualItemID'=>'CFS-00007',  'categoryID'=>26,'name'=> 'Tuna with Chili & Garlic', 'unitOfMeasurement'=>'80 G', 'description'=>''],
							['itemID'=>50, 'virtualItemID'=>'CFS-00008',  'categoryID'=>26,'name'=> 'Sardines in Sunflower Oil', 'unitOfMeasurement'=>'120 G', 'description'=>''],
							['itemID'=>51, 'virtualItemID'=>'CFS-00009',  'categoryID'=>26,'name'=> 'Fried Dace with Salted Blk Beans', 'unitOfMeasurement'=>'150 G', 'description'=>''],
							['itemID'=>52, 'virtualItemID'=>'CFS-00010',  'categoryID'=>26,'name'=> 'Fried Dace', 'unitOfMeasurement'=>'227 G', 'description'=>''],
							['itemID'=>53, 'virtualItemID'=>'CFR-00001',  'categoryID'=>27,'name'=> 'Fiesta Fruit Cocktail', 'unitOfMeasurement'=>'439 G', 'description'=>''],
							['itemID'=>54, 'virtualItemID'=>'CFR-00002',  'categoryID'=>27,'name'=> 'Del Monte Sliced Pineapple in Heavy Syrup [S]', 'unitOfMeasurement'=>'234 G', 'description'=>''],
							['itemID'=>55, 'virtualItemID'=>'CFR-00003',  'categoryID'=>27,'name'=> 'Del Monte Sliced Pineapple in Heavy Syrup [L]', 'unitOfMeasurement'=>'836 G', 'description'=>''],
							['itemID'=>56, 'virtualItemID'=>'CFR-00004',  'categoryID'=>27,'name'=> 'Del Monte Fruit Cocktail [S]', 'unitOfMeasurement'=>'8 OZ', 'description'=>''],
							['itemID'=>57, 'virtualItemID'=>'CFR-00005',  'categoryID'=>27,'name'=> 'Del Monte Fruit Cocktail [M]', 'unitOfMeasurement'=>'420 G', 'description'=>''],
							['itemID'=>58, 'virtualItemID'=>'CFR-00006',  'categoryID'=>27,'name'=> 'Del Monte Fruit Cocktail [L]', 'unitOfMeasurement'=>'825 G', 'description'=>''],
							['itemID'=>59, 'virtualItemID'=>'CFR-00007',  'categoryID'=>27,'name'=> 'Del Monte Fiesta Tropical Fruit Cocktail [L]', 'unitOfMeasurement'=>'30 OZ', 'description'=>''],
							['itemID'=>60, 'virtualItemID'=>'CFR-00008',  'categoryID'=>27,'name'=> 'Del Monte Fiesta Tropical Fruit Cocktail [M]', 'unitOfMeasurement'=>'439 G', 'description'=>''],
							['itemID'=>61, 'virtualItemID'=>'CFR-00009',  'categoryID'=>27,'name'=> 'Del Monte Peach Slices [S]', 'unitOfMeasurement'=>'225 G', 'description'=>''],
							['itemID'=>62, 'virtualItemID'=>'CMT-00001',  'categoryID'=>28,'name'=> 'Organic Bockwurst Sausage 6\'s', 'unitOfMeasurement'=>'180 G', 'description'=>''],
							['itemID'=>63, 'virtualItemID'=>'CMT-00002',  'categoryID'=>28,'name'=> 'Organic Vienna Sausage 6\'s', 'unitOfMeasurement'=>'250 G', 'description'=>''],
							['itemID'=>64, 'virtualItemID'=>'CMT-00003',  'categoryID'=>28,'name'=> 'Premium Ham Luncheon Meat', 'unitOfMeasurement'=>'198 G', 'description'=>''],
							['itemID'=>65, 'virtualItemID'=>'CMT-00004',  'categoryID'=>28,'name'=> 'Pork Luncheon Meat', 'unitOfMeasurement'=>'340 G', 'description'=>''],
							['itemID'=>66, 'virtualItemID'=>'CMT-00005',  'categoryID'=>28,'name'=> 'Pork Luncheon Meat - Japstyle', 'unitOfMeasurement'=>'340 G', 'description'=>''],
							['itemID'=>67, 'virtualItemID'=>'CMT-00006',  'categoryID'=>28,'name'=> 'Chopped Pork and Ham','unitOfMeasurement'=>'198 G', 'description'=>''],
							['itemID'=>68, 'virtualItemID'=>'CMT-00007',  'categoryID'=>28,'name'=> 'Chopped Pork and Ham', 'unitOfMeasurement'=>'340 G', 'description'=>''],
							['itemID'=>69, 'virtualItemID'=>'CMT-00008',  'categoryID'=>28,'name'=> 'Chopped Pork and Ham', 'unitOfMeasurement'=>'397 G', 'description'=>''],
							['itemID'=>70, 'virtualItemID'=>'CMT-00009',  'categoryID'=>28,'name'=> 'Corned Beef', 'unitOfMeasurement'=>'170 G', 'description'=>''],
							['itemID'=>71, 'virtualItemID'=>'CMT-00010',  'categoryID'=>28,'name'=> 'Corned Beef [Round]', 'unitOfMeasurement'=>'340 G', 'description'=>''],
							['itemID'=>72, 'virtualItemID'=>'CMT-00011',  'categoryID'=>28,'name'=> 'Corned Beef [Rectangular]', 'unitOfMeasurement'=>'340 G', 'description'=>''],
							['itemID'=>73, 'virtualItemID'=>'CMT-00012',  'categoryID'=>28,'name'=> 'Luncheon Meat', 'unitOfMeasurement'=>'198 G', 'description'=>''],
							['itemID'=>74, 'virtualItemID'=>'CMT-00013',  'categoryID'=>28,'name'=> 'Luncheon Meat [Less Sodium]', 'unitOfMeasurement'=>'340 G', 'description'=>''],
							['itemID'=>75, 'virtualItemID'=>'CPK-00001',  'categoryID'=>29,'name'=> 'Stuffed Green Olives with Pimnto', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>76, 'virtualItemID'=>'CPK-00002',  'categoryID'=>29,'name'=> 'Ci Crushed Chili', 'unitOfMeasurement'=>'180 G', 'description'=>''],
							['itemID'=>77, 'virtualItemID'=>'CPK-00003',  'categoryID'=>29,'name'=> 'Pitted Black Olives', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>78, 'virtualItemID'=>'CPK-00004',  'categoryID'=>29,'name'=> 'Olive with Papricka', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>79, 'virtualItemID'=>'CPK-00005',  'categoryID'=>29,'name'=> 'Cacerena Blk Pitted Olives', 'unitOfMeasurement'=>'350 G', 'description'=>''],
							['itemID'=>80, 'virtualItemID'=>'CPK-00006',  'categoryID'=>29,'name'=> 'Manzanilla Green Pitted Olives', 'unitOfMeasurement'=>'235 G', 'description'=>''],
							['itemID'=>81, 'virtualItemID'=>'CPK-00007',  'categoryID'=>29,'name'=> 'Gherkins Extra Thin', 'unitOfMeasurement'=>'185 G', 'description'=>''],
							['itemID'=>82, 'virtualItemID'=>'CPK-00008',  'categoryID'=>29,'name'=> 'Bitter-Sweet Gherkin Casino', 'unitOfMeasurement'=>'360 G', 'description'=>''],
							['itemID'=>83, 'virtualItemID'=>'CPK-00009',  'categoryID'=>29,'name'=> 'Pitted Olives with Herb & Garlic', 'unitOfMeasurement'=>'70 G', 'description'=>''],
							['itemID'=>84, 'virtualItemID'=>'CPK-00010',  'categoryID'=>29,'name'=> 'Gherkins', 'unitOfMeasurement'=>'370 G', 'description'=>''],
							['itemID'=>85, 'virtualItemID'=>'CPBC-00001', 'categoryID'=>30,'name'=> 'Wet Bean Curd [with Chili]', 'unitOfMeasurement'=>'280 G', 'description'=>''],
							['itemID'=>86, 'virtualItemID'=>'CPBC-00002', 'categoryID'=>30,'name'=> 'Wet Red Bean Curd', 'unitOfMeasurement'=>'280 G', 'description'=>''],
							['itemID'=>87, 'virtualItemID'=>'CPBC-00003', 'categoryID'=>30,'name'=> 'Wet Bean Curd', 'unitOfMeasurement'=>'280 G', 'description'=>''],
							['itemID'=>88, 'virtualItemID'=>'CPBC-00004', 'categoryID'=>30,'name'=> 'Sichuan Hot Beancurd', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>89, 'virtualItemID'=>'CPBC-00005', 'categoryID'=>30,'name'=> 'Sichuan Hot Beancurd', 'unitOfMeasurement'=>'130 G', 'description'=>''],
							['itemID'=>90, 'virtualItemID'=>'CPBC-00006', 'categoryID'=>30,'name'=> 'Sichuan Beancurd', 'unitOfMeasurement'=>'130 G', 'description'=>''],
							['itemID'=>91, 'virtualItemID'=>'CPBC-00007', 'categoryID'=>30,'name'=> 'Chili Bean Curd', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>92, 'virtualItemID'=>'CSP-00001',  'categoryID'=>31,'name'=> 'Organic Chicken Broth Pacific', 'unitOfMeasurement'=>'946 ML', 'description'=>''],
							['itemID'=>93, 'virtualItemID'=>'CSP-00002',  'categoryID'=>31,'name'=> 'Imagine Organic Low Sodium Free Range Chicken Broth', 'unitOfMeasurement'=>'32 OZ', 'description'=>''],
							['itemID'=>94, 'virtualItemID'=>'CSP-00003',  'categoryID'=>31,'name'=> 'Imagine Organic Creamy Potato Leek Soup', 'unitOfMeasurement'=>'32 OZ', 'description'=>''],
							['itemID'=>95, 'virtualItemID'=>'CSP-00004',  'categoryID'=>31,'name'=> 'Organic Vegetable Soup', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>96, 'virtualItemID'=>'CSP-00005',  'categoryID'=>31,'name'=> 'Clear Chicken Broth', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>97, 'virtualItemID'=>'CSP-00006',  'categoryID'=>31,'name'=> 'Pork Bone Broth', 'unitOfMeasurement'=>'500 ML', 'description'=>''],
							['itemID'=>98, 'virtualItemID'=>'CSP-00007',  'categoryID'=>31,'name'=> 'Pork Bone Broth', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>99, 'virtualItemID'=>'CSP-00008',  'categoryID'=>31,'name'=> 'Fish Broth', 'unitOfMeasurement'=>'500 ML', 'description'=>''],
							['itemID'=>100,'virtualItemID'=>'CSP-00009',  'categoryID'=>31,'name'=> 'Supperior Broth Ham Flavoured', 'unitOfMeasurement'=>'250 ML', 'description'=>''],
							['itemID'=>101,'virtualItemID'=>'CSP-00010',  'categoryID'=>31,'name'=> 'Supperior Broth Scallop Flavoured', 'unitOfMeasurement'=>'250 ML', 'description'=>''],
							['itemID'=>102,'virtualItemID'=>'CSP-00011',  'categoryID'=>31,'name'=> 'Cream of Mushroom Soup', 'unitOfMeasurement'=>'295 G', 'description'=>''],
							['itemID'=>103,'virtualItemID'=>'CSP-00012',  'categoryID'=>31,'name'=> 'Cream of Mushroom Soup', 'unitOfMeasurement'=>'405 G', 'description'=>''],
							['itemID'=>104,'virtualItemID'=>'CSP-00013',  'categoryID'=>31,'name'=> 'Cream of Mushroom [98 Per. Fat Free]', 'unitOfMeasurement'=>'298 G', 'description'=>''],
							['itemID'=>105,'virtualItemID'=>'CSP-00014',  'categoryID'=>31,'name'=> 'Mushroom & Potato Soup', 'unitOfMeasurement'=>'305 G', 'description'=>''],
							['itemID'=>106,'virtualItemID'=>'CVT-00001',  'categoryID'=>32,'name'=> 'Organic Chili Beans', 'unitOfMeasurement'=>'15 OZ', 'description'=>''],
							['itemID'=>107,'virtualItemID'=>'CVT-00002',  'categoryID'=>32,'name'=> 'Organic Natural Tomato', 'unitOfMeasurement'=>'660 G', 'description'=>''],
							['itemID'=>108,'virtualItemID'=>'CVT-00003',  'categoryID'=>32,'name'=> 'Organic Tomato Basil Pulp', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>109,'virtualItemID'=>'CVT-00004',  'categoryID'=>32,'name'=> 'Organic Tomato Pulp', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>110,'virtualItemID'=>'CVT-00005',  'categoryID'=>32,'name'=> 'Baked Beans with Tomato Sauce', 'unitOfMeasurement'=>'415 G', 'description'=>''],
							['itemID'=>111,'virtualItemID'=>'CVT-00006',  'categoryID'=>32,'name'=> 'Beans with Pork Sausages', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>112,'virtualItemID'=>'CVT-00007',  'categoryID'=>32,'name'=> 'Spaghetti with Tomato Sauce', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>113,'virtualItemID'=>'CVT-00008',  'categoryID'=>32,'name'=> 'Del Monte Peeled Diced Tomatoes', 'unitOfMeasurement'=>'411 G', 'description'=>''],
							['itemID'=>114,'virtualItemID'=>'CVT-00009',  'categoryID'=>32,'name'=> 'Del Monte Sweet Peas [L]', 'unitOfMeasurement'=>'425 G', 'description'=>''],
							['itemID'=>115,'virtualItemID'=>'CVT-00010',  'categoryID'=>32,'name'=> 'Del Stewed Tomatoes - Original', 'unitOfMeasurement'=>'14.5 OZ', 'description'=>''],
							['itemID'=>116,'virtualItemID'=>'CVT-00011',  'categoryID'=>32,'name'=> 'Del Stewed Tomatoes - Mexican', 'unitOfMeasurement'=>'411 G', 'description'=>''],
							['itemID'=>117,'virtualItemID'=>'ANND-00001', 'categoryID'=>33,'name'=> 'Sau Tao Abalone Noodle', 'unitOfMeasurement'=>'12 PCS', 'description'=>''],
							['itemID'=>118,'virtualItemID'=>'ANND-00002', 'categoryID'=>33,'name'=> 'Sapporo Ichiban Salt 5\'s', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>119,'virtualItemID'=>'ANND-00003', 'categoryID'=>33,'name'=> 'Sau Tao Shrimp-Egg Noodles [Thin]', 'unitOfMeasurement'=>'454 G', 'description'=>''],
							['itemID'=>120,'virtualItemID'=>'ANND-00004', 'categoryID'=>33,'name'=> 'Sau Tao Shrimp-Egg Noodles [Thin]', 'unitOfMeasurement'=>'880 G', 'description'=>''],
							['itemID'=>121,'virtualItemID'=>'ANND-00005', 'categoryID'=>33,'name'=> 'Sau Tao Authentic Scallop Noodles', 'unitOfMeasurement'=>'454 G', 'description'=>''],
							['itemID'=>122,'virtualItemID'=>'ANND-00006', 'categoryID'=>33,'name'=> 'Sau Tao Scallop Noodles', 'unitOfMeasurement'=>'880 G', 'description'=>''],
							['itemID'=>123,'virtualItemID'=>'ANND-00007', 'categoryID'=>33,'name'=> 'Sau Tao - Abalone Noodle', 'unitOfMeasurement'=>'880 G', 'description'=>''],
							['itemID'=>124,'virtualItemID'=>'ANND-00008', 'categoryID'=>33,'name'=> 'Sau Tao Spinach Noodles', 'unitOfMeasurement'=>'454 G', 'description'=>''],
							['itemID'=>125,'virtualItemID'=>'ANND-00009', 'categoryID'=>33,'name'=> 'Sau Tao E-Fu Noodle [Chinese Ham & Abalone Soup Flavour]', 'unitOfMeasurement'=>'160 G', 'description'=>''],
							['itemID'=>126,'virtualItemID'=>'CSO-00001',  'categoryID'=>34,'name'=> 'Organic Refined Sunflower Oil', 'unitOfMeasurement'=>'32 OZ', 'description'=>''],
							['itemID'=>127,'virtualItemID'=>'CSO-00002',  'categoryID'=>34,'name'=> 'Organic Sunflower Oil', 'unitOfMeasurement'=>'16 OZ', 'description'=>''],
							['itemID'=>128,'virtualItemID'=>'CSO-00003',  'categoryID'=>34,'name'=> 'Organic Sunflower Seed Oil', 'unitOfMeasurement'=>'750 ML', 'description'=>''],
							['itemID'=>129,'virtualItemID'=>'CSO-00004',  'categoryID'=>34,'name'=> 'Canola Oil', 'unitOfMeasurement'=>'900 ML', 'description'=>''],
							['itemID'=>130,'virtualItemID'=>'CSO-00005',  'categoryID'=>34,'name'=> 'Canola Oil', 'unitOfMeasurement'=>'2 L', 'description'=>''],
							['itemID'=>131,'virtualItemID'=>'CSO-00006',  'categoryID'=>34,'name'=> 'Canola Oil', 'unitOfMeasurement'=>'5 L', 'description'=>''],
							['itemID'=>132,'virtualItemID'=>'CSO-00007',  'categoryID'=>34,'name'=> 'Canola Oil', 'unitOfMeasurement'=>'600 ML', 'description'=>''],
							['itemID'=>133,'virtualItemID'=>'CSO-00008',  'categoryID'=>34,'name'=> 'Dha Canola Oil', 'unitOfMeasurement'=>'900 ML', 'description'=>''],
							['itemID'=>134,'virtualItemID'=>'CSO-00009',  'categoryID'=>34,'name'=> 'Pure Canola Oil', 'unitOfMeasurement'=>'5.5L', 'description'=>''],
							['itemID'=>135,'virtualItemID'=>'CSO-00010',  'categoryID'=>34,'name'=> 'Pure Canola Oil', 'unitOfMeasurement'=>'3L', 'description'=>''],
							['itemID'=>136,'virtualItemID'=>'CSO-00011',  'categoryID'=>34,'name'=> 'Pure Canola Oil', 'unitOfMeasurement'=>'750 ML', 'description'=>''],
							['itemID'=>137,'virtualItemID'=>'COO-00001',  'categoryID'=>35,'name'=> 'Corn Oil', 'unitOfMeasurement'=>'5L', 'description'=>''],
							['itemID'=>138,'virtualItemID'=>'COO-00002',  'categoryID'=>35,'name'=> 'Corn Oil', 'unitOfMeasurement'=>'2 L', 'description'=>''],
							['itemID'=>139,'virtualItemID'=>'COO-00003',  'categoryID'=>35,'name'=> 'Pure Corn Oil', 'unitOfMeasurement'=>'5.5 L', 'description'=>''],
							['itemID'=>140,'virtualItemID'=>'COO-00004',  'categoryID'=>35,'name'=> 'Knife Pure Corn Oil', 'unitOfMeasurement'=>'750 ML', 'description'=>''],
							['itemID'=>141,'virtualItemID'=>'INND-00001', 'categoryID'=>36,'name'=> 'Nissen De Ma E Seasam Oil Instant Noodle', 'unitOfMeasurement'=>'5 PCS', 'description'=>''],
							['itemID'=>142,'virtualItemID'=>'INND-00002', 'categoryID'=>36,'name'=> 'Nissen De Ma E Noofle Tonkotsu', 'unitOfMeasurement'=>'5 PCS', 'description'=>''],
							['itemID'=>143,'virtualItemID'=>'INND-00003', 'categoryID'=>36,'name'=> 'Nissen De Ma E Instant Noodle - Chicken', 'unitOfMeasurement'=>'5 PCS', 'description'=>''],
							['itemID'=>144,'virtualItemID'=>'INND-00004', 'categoryID'=>36,'name'=> 'Nissen De Ma E Instant Noodle - Beef', 'unitOfMeasurement'=>'5 PCS', 'description'=>''],
							['itemID'=>145,'virtualItemID'=>'INND-00005', 'categoryID'=>36,'name'=> 'Nissen De Ma E Instant Noodle - Spicy', 'unitOfMeasurement'=>'5 PCS', 'description'=>''],
							['itemID'=>146,'virtualItemID'=>'INND-00006', 'categoryID'=>36,'name'=> 'Nissen De Ma E Instant Noodle - Curry', 'unitOfMeasurement'=>'5 PCS', 'description'=>''],
							['itemID'=>147,'virtualItemID'=>'INND-00007', 'categoryID'=>36,'name'=> 'Shin Ramen', 'unitOfMeasurement'=>'5 PCS', 'description'=>''],
							['itemID'=>148,'virtualItemID'=>'INND-00008', 'categoryID'=>36,'name'=> 'Noodle Shin Ramyun', 'unitOfMeasurement'=>'5 PCS', 'description'=>''],
							['itemID'=>149,'virtualItemID'=>'INND-00009', 'categoryID'=>36,'name'=> 'Korean Clay Pot Ramyun', 'unitOfMeasurement'=>'5 PCS', 'description'=>''],
							['itemID'=>150,'virtualItemID'=>'INND-00010', 'categoryID'=>36,'name'=> 'Kimchi Noodle', 'unitOfMeasurement'=>'5 PCS', 'description'=>''],
							['itemID'=>151,'virtualItemID'=>'PAS-00001',  'categoryID'=>37,'name'=> 'Organic Penne Rigate', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>152,'virtualItemID'=>'PAS-00002',  'categoryID'=>37,'name'=> 'Roasted Garlic & Olive Oil Couscous', 'unitOfMeasurement'=>'7 OZ', 'description'=>''],
							['itemID'=>153,'virtualItemID'=>'PAS-00003',  'categoryID'=>37,'name'=> 'Organic Tricolor Quinoa', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>154,'virtualItemID'=>'PAS-00004',  'categoryID'=>37,'name'=> 'Organic Flax Seeds', 'unitOfMeasurement'=>'1 LB', 'description'=>''],
							['itemID'=>155,'virtualItemID'=>'PAS-00005',  'categoryID'=>37,'name'=> 'Organic Spelt Wholegrain Penne', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>156,'virtualItemID'=>'PAS-00006',  'categoryID'=>37,'name'=> 'Lasagna 189', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>157,'virtualItemID'=>'PAS-00007',  'categoryID'=>37,'name'=> 'Cellentani', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>158,'virtualItemID'=>'PAS-00008',  'categoryID'=>37,'name'=> 'Farfalle #65', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>159,'virtualItemID'=>'PEAO-00001', 'categoryID'=>38,'name'=> 'Peanut Oil', 'unitOfMeasurement'=>'900 ML', 'description'=>''],
							['itemID'=>160,'virtualItemID'=>'PEAO-00002', 'categoryID'=>38,'name'=> 'Peanut Oil', 'unitOfMeasurement'=>'2 L', 'description'=>''],
							['itemID'=>161,'virtualItemID'=>'PEAO-00003', 'categoryID'=>38,'name'=> 'Extra Virgin Peanut Oil', 'unitOfMeasurement'=>'5 L', 'description'=>''],
							['itemID'=>162,'virtualItemID'=>'PEAO-00004', 'categoryID'=>38,'name'=> 'Extra Virgin Peanut Oil', 'unitOfMeasurement'=>'900 ML', 'description'=>''],
							['itemID'=>163,'virtualItemID'=>'PEAO-00005', 'categoryID'=>38,'name'=> 'Peanut Aroma Nutritious Oil', 'unitOfMeasurement'=>'5 L', 'description'=>''],
							['itemID'=>164,'virtualItemID'=>'PEAO-00006', 'categoryID'=>38,'name'=> 'Peanut Aroma Nutritious Oil', 'unitOfMeasurement'=>'900 ML', 'description'=>''],
							['itemID'=>165,'virtualItemID'=>'SPER-00001', 'categoryID'=>39,'name'=> 'Organic Millet', 'unitOfMeasurement'=>'1 KG', 'description'=>''],
							['itemID'=>166,'virtualItemID'=>'SPER-00002', 'categoryID'=>39,'name'=> 'Organic Basmatic Rice', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>167,'virtualItemID'=>'SPER-00003', 'categoryID'=>39,'name'=> 'Organic Rice Trio', 'unitOfMeasurement'=>'1 KG', 'description'=>''],
							['itemID'=>168,'virtualItemID'=>'SPER-00004', 'categoryID'=>39,'name'=> 'Organic Jasmine Rice', 'unitOfMeasurement'=>'1 KG', 'description'=>''],
							['itemID'=>169,'virtualItemID'=>'SPER-00005', 'categoryID'=>39,'name'=> 'Organic Ten Grains Rice', 'unitOfMeasurement'=>'1 KG', 'description'=>''],
							['itemID'=>170,'virtualItemID'=>'SPER-00006', 'categoryID'=>39,'name'=> 'Organic Semi Brown Rice', 'unitOfMeasurement'=>'1 KG', 'description'=>''],
							['itemID'=>171,'virtualItemID'=>'SPER-00007', 'categoryID'=>39,'name'=> 'Organic Milled Rice', 'unitOfMeasurement'=>'1.5 KG', 'description'=>''],
							['itemID'=>172,'virtualItemID'=>'SPER-00008', 'categoryID'=>39,'name'=> 'Green Dot Dot Organic Black Rice', 'unitOfMeasurement'=>'1 KG', 'description'=>''],
							['itemID'=>173,'virtualItemID'=>'SPER-00009', 'categoryID'=>39,'name'=> 'Green Dot Dot Organic Gaba Brown Rice', 'unitOfMeasurement'=>'1 KG', 'description'=>''],
							['itemID'=>174,'virtualItemID'=>'SPER-00010', 'categoryID'=>39,'name'=> 'Organic Brown Rice', 'unitOfMeasurement'=>'1.5 KG', 'description'=>''],
							['itemID'=>175,'virtualItemID'=>'VEOTHCO-00001', 'categoryID'=>40,'name'=> 'Organic Refined Coconut Oil', 'unitOfMeasurement'=>'14 OZ', 'description'=>''],
							['itemID'=>176,'virtualItemID'=>'VEOTHCO-00002', 'categoryID'=>40,'name'=> 'Organic Cold-Pressed Flax Oil', 'unitOfMeasurement'=>'12 OZ', 'description'=>''],
							['itemID'=>177,'virtualItemID'=>'VEOTHCO-00003', 'categoryID'=>40,'name'=> 'Grapeseed Oil', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>178,'virtualItemID'=>'VEOTHCO-00004', 'categoryID'=>40,'name'=> 'Blended Cooking Oil', 'unitOfMeasurement'=>'5 L', 'description'=>''],
							['itemID'=>179,'virtualItemID'=>'VEOTHCO-00005', 'categoryID'=>40,'name'=> 'Grapeseed Oil', 'unitOfMeasurement'=>'750 ML', 'description'=>''],
							['itemID'=>180,'virtualItemID'=>'VEOTHCO-00006', 'categoryID'=>40,'name'=> 'Rice Bran Oil', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>181,'virtualItemID'=>'WHR-00001',     'categoryID'=>41,'name'=> 'Pearl Rice', 'unitOfMeasurement'=>'1.5 KG', 'description'=>''],
							['itemID'=>182,'virtualItemID'=>'WHR-00002',     'categoryID'=>41,'name'=> 'Thai Rice', 'unitOfMeasurement'=>'8 KG', 'description'=>''],
							['itemID'=>183,'virtualItemID'=>'WHR-00003',     'categoryID'=>41,'name'=> 'Pearl Rice', 'unitOfMeasurement'=>'2 KG', 'description'=>''],
							['itemID'=>184,'virtualItemID'=>'WHR-00004',     'categoryID'=>41,'name'=> 'Premium Thai Hom Mali Rice', 'unitOfMeasurement'=>'8 KG', 'description'=>''],
							['itemID'=>185,'virtualItemID'=>'WHR-00005',     'categoryID'=>41,'name'=> 'Thai Premium Rice', 'unitOfMeasurement'=>'2 KG', 'description'=>''],
							['itemID'=>186,'virtualItemID'=>'WHR-00006',     'categoryID'=>41,'name'=> 'Premium Jasmine Rice', 'unitOfMeasurement'=>'1.5 KG', 'description'=>''],
							['itemID'=>187,'virtualItemID'=>'WHR-00007',     'categoryID'=>41,'name'=> 'Premium Jasmine Rice', 'unitOfMeasurement'=>'15 KG', 'description'=>''],
							['itemID'=>188,'virtualItemID'=>'WHR-00008',     'categoryID'=>41,'name'=> 'Thai Hom Mali Fragrant Rice', 'unitOfMeasurement'=>'1.5 KG', 'description'=>''],
							['itemID'=>189,'virtualItemID'=>'WHR-00009',     'categoryID'=>41,'name'=> 'Thai Hom Mali Fragrant Rice', 'unitOfMeasurement'=>'15 KG', 'description'=>''],
							['itemID'=>190,'virtualItemID'=>'WHR-00010',     'categoryID'=>41,'name'=> 'Thai Hom Mali Fragrant Rice', 'unitOfMeasurement'=>'2 KG', 'description'=>''],
							['itemID'=>191,'virtualItemID'=>'BDN-00001',     'categoryID'=>42,'name'=> 'Organic Flour Plain White', 'unitOfMeasurement'=>'1.5 KG', 'description'=>''],
							['itemID'=>192,'virtualItemID'=>'BDN-00002',     'categoryID'=>42,'name'=> 'Pancake Mix', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>193,'virtualItemID'=>'BDN-00003',     'categoryID'=>42,'name'=> 'Gold Medal Flour', 'unitOfMeasurement'=>'907 G', 'description'=>''],
							['itemID'=>194,'virtualItemID'=>'BDN-00004',     'categoryID'=>42,'name'=> 'Cookie Mix Choco Chip', 'unitOfMeasurement'=>'17.5 OZ', 'description'=>''],
							['itemID'=>195,'virtualItemID'=>'BDN-00005',     'categoryID'=>42,'name'=> 'Fudge Brownie Mix', 'unitOfMeasurement'=>'18.3 OZ', 'description'=>''],
							['itemID'=>196,'virtualItemID'=>'BDN-00006',     'categoryID'=>42,'name'=> 'Supermoist Tellow Cakemix', 'unitOfMeasurement'=>'18.25 OZ', 'description'=>''],
							['itemID'=>197,'virtualItemID'=>'BDN-00007',     'categoryID'=>42,'name'=> 'Cookie Mix Oatmeal Choco Chip', 'unitOfMeasurement'=>'17.5 OZ', 'description'=>''],
							['itemID'=>198,'virtualItemID'=>'BDN-00008',     'categoryID'=>42,'name'=> 'Blueberry Muffin Mix', 'unitOfMeasurement'=>'479 G', 'description'=>''],
							['itemID'=>199,'virtualItemID'=>'CONSC-00001',   'categoryID'=>43,'name'=> 'Freshly Minced Garlic', 'unitOfMeasurement'=>'213 G', 'description'=>''],
							['itemID'=>200,'virtualItemID'=>'CONSC-00002',   'categoryID'=>43,'name'=> 'Black Bean & Garlic Sauce', 'unitOfMeasurement'=>'226 G', 'description'=>''],
							['itemID'=>201,'virtualItemID'=>'CONSC-00003',   'categoryID'=>43,'name'=> 'Char Siu Sauce', 'unitOfMeasurement'=>'240 G', 'description'=>''],
							['itemID'=>202,'virtualItemID'=>'CONSC-00004',   'categoryID'=>43,'name'=> 'Black Pepper Sauce', 'unitOfMeasurement'=>'230 G', 'description'=>''],
							['itemID'=>203,'virtualItemID'=>'CONSC-00005',   'categoryID'=>43,'name'=> 'Chili Galic Sauce', 'unitOfMeasurement'=>'226 G', 'description'=>''],
							['itemID'=>204,'virtualItemID'=>'CONSC-00006',   'categoryID'=>43,'name'=> 'Fine Shrimp Sauce', 'unitOfMeasurement'=>'227 G', 'description'=>''],
							['itemID'=>205,'virtualItemID'=>'CONSC-00007',   'categoryID'=>43,'name'=> 'Hoisin Sauce', 'unitOfMeasurement'=>'240 G', 'description'=>''],
							['itemID'=>206,'virtualItemID'=>'CONSC-00008',   'categoryID'=>43,'name'=> 'Chu Hou Paste', 'unitOfMeasurement'=>'240 G', 'description'=>''],
							['itemID'=>207,'virtualItemID'=>'CONSC-00009',   'categoryID'=>43,'name'=> 'Minced Ginger', 'unitOfMeasurement'=>'213 G', 'description'=>''],
							['itemID'=>208,'virtualItemID'=>'CONSC-00010',   'categoryID'=>43,'name'=> 'Coconut Curry Sauce', 'unitOfMeasurement'=>'235 G', 'description'=>''],
							['itemID'=>209,'virtualItemID'=>'CONSC-00011',   'categoryID'=>43,'name'=> 'Sa Cha Sauce', 'unitOfMeasurement'=>'198 G', 'description'=>''],
							['itemID'=>210,'virtualItemID'=>'CONSC-00012',   'categoryID'=>43,'name'=> 'Spicy Chili Stir-Fly Sauce', 'unitOfMeasurement'=>'235 G', 'description'=>''],
							['itemID'=>211,'virtualItemID'=>'CONSC-00013',   'categoryID'=>43,'name'=> 'Satay Sauce', 'unitOfMeasurement'=>'220 G', 'description'=>''],
							['itemID'=>212,'virtualItemID'=>'CONSC-00014',   'categoryID'=>43,'name'=> 'Sichuan Hot & Spicy Sauce', 'unitOfMeasurement'=>'230 G', 'description'=>''],
							['itemID'=>213,'virtualItemID'=>'CONSC-00015',   'categoryID'=>43,'name'=> 'Spicy Black Bean Sauce', 'unitOfMeasurement'=>'226 G', 'description'=>''],
							['itemID'=>214,'virtualItemID'=>'CCSXSC-00001',  'categoryID'=>44,'name'=> 'XO Sauce', 'unitOfMeasurement'=>'220 G', 'description'=>''],
							['itemID'=>215,'virtualItemID'=>'CCSXSC-00002',  'categoryID'=>44,'name'=> 'XO Sauce Extra Hot', 'unitOfMeasurement'=>'220 G', 'description'=>''],
							['itemID'=>216,'virtualItemID'=>'CCSXSC-00003',  'categoryID'=>44,'name'=> 'XO Sauce', 'unitOfMeasurement'=>'80 G', 'description'=>''],
							['itemID'=>217,'virtualItemID'=>'CCSXSC-00004',  'categoryID'=>44,'name'=> 'XO Sauce Extra Hot', 'unitOfMeasurement'=>'80 G', 'description'=>''],
							['itemID'=>218,'virtualItemID'=>'CCSXSC-00005',  'categoryID'=>44,'name'=> 'Seafood XO Sauce', 'unitOfMeasurement'=>'80 G', 'description'=>''],
							['itemID'=>219,'virtualItemID'=>'CCSXSC-00006',  'categoryID'=>44,'name'=> 'Chiu Chow Chili Oil', 'unitOfMeasurement'=>'205 G', 'description'=>''],
							['itemID'=>220,'virtualItemID'=>'CCSXSC-00007',  'categoryID'=>44,'name'=> 'Chiu Chow Chili Oil', 'unitOfMeasurement'=>'85 G', 'description'=>''],
							['itemID'=>221,'virtualItemID'=>'CCSXSC-00008',  'categoryID'=>44,'name'=> 'Chili Bean Sauce [Toban Djan]', 'unitOfMeasurement'=>'240 G', 'description'=>''],
							['itemID'=>222,'virtualItemID'=>'CCSXSC-00009',  'categoryID'=>44,'name'=> 'Fine Chili Sauce', 'unitOfMeasurement'=>'226 G', 'description'=>''],
							['itemID'=>223,'virtualItemID'=>'CCSXSC-00010',  'categoryID'=>44,'name'=> 'Guilin Style Chili Sauce', 'unitOfMeasurement'=>'230 G', 'description'=>''],
							['itemID'=>224,'virtualItemID'=>'KPSCTP-00001',  'categoryID'=>45,'name'=> 'Organic Strained Tomatoes Puree', 'unitOfMeasurement'=>'700 G', 'description'=>''],
							['itemID'=>225,'virtualItemID'=>'KPSCTP-00002',  'categoryID'=>45,'name'=> 'Organic Ketchup', 'unitOfMeasurement'=>'280 G', 'description'=>''],
							['itemID'=>226,'virtualItemID'=>'KPSCTP-00003',  'categoryID'=>45,'name'=> 'Sugo Bolognese', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>227,'virtualItemID'=>'KPSCTP-00004',  'categoryID'=>45,'name'=> 'Pesto Genovese', 'unitOfMeasurement'=>'190 G', 'description'=>''],
							['itemID'=>228,'virtualItemID'=>'KPSCTP-00005',  'categoryID'=>45,'name'=> 'Sugo Con Sasilico', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>229,'virtualItemID'=>'KPSCTP-00006',  'categoryID'=>45,'name'=> 'Arrabbiata Pasta Sauce', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>230,'virtualItemID'=>'KPSCTP-00007',  'categoryID'=>45,'name'=> 'Pesto Rosso', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>231,'virtualItemID'=>'KPSCTP-00008',  'categoryID'=>45,'name'=> 'Salsa Napoletana', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>232,'virtualItemID'=>'KPSCTP-00009',  'categoryID'=>45,'name'=> 'Puttanesca Pasta Sauce', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>233,'virtualItemID'=>'PHS-00001',     'categoryID'=>46,'name'=> 'Organic Ground Turmeric', 'unitOfMeasurement'=>'1.6 OZ', 'description'=>''],
							['itemID'=>234,'virtualItemID'=>'PHS-00002',     'categoryID'=>46,'name'=> 'Organic Rosemary', 'unitOfMeasurement'=>'0.6 OZ', 'description'=>''],
							['itemID'=>235,'virtualItemID'=>'PHS-00003',     'categoryID'=>46,'name'=> 'Organic Thyme', 'unitOfMeasurement'=>'0.6 OZ', 'description'=>''],
							['itemID'=>236,'virtualItemID'=>'PHS-00004',     'categoryID'=>46,'name'=> 'Organic Ground Cinnamon','unitOfMeasurement'=> '1.7 OZ', 'description'=>''],
							['itemID'=>237,'virtualItemID'=>'PHS-00005',     'categoryID'=>46,'name'=> 'Organic Parsley Flakes', 'unitOfMeasurement'=>'0.23 OZ', 'description'=>''],
							['itemID'=>238,'virtualItemID'=>'PHS-00006',     'categoryID'=>46,'name'=> 'Organic Peppercorns Black', 'unitOfMeasurement'=>'40 G', 'description'=>''],
							['itemID'=>239,'virtualItemID'=>'PHS-00007',     'categoryID'=>46,'name'=> 'Organic Oregano', 'unitOfMeasurement'=>'0.45 OZ', 'description'=>''],
							['itemID'=>240,'virtualItemID'=>'PHS-00008',     'categoryID'=>46,'name'=> 'Organic Groun Paprika', 'unitOfMeasurement'=>'1.4 OZ', 'description'=>''],
							['itemID'=>241,'virtualItemID'=>'PHS-00009',     'categoryID'=>46,'name'=> 'Organic Curry Powder', 'unitOfMeasurement'=>'37 G', 'description'=>''],
							['itemID'=>242,'virtualItemID'=>'PHS-00010',     'categoryID'=>46,'name'=> 'Organic Cumin Ground', 'unitOfMeasurement'=>'50 G', 'description'=>''],
							['itemID'=>243,'virtualItemID'=>'PHS-00011',     'categoryID'=>46,'name'=> 'Ground White Pepper', 'unitOfMeasurement'=>'56 G', 'description'=>''],
							['itemID'=>244,'virtualItemID'=>'PHS-00012',     'categoryID'=>46,'name'=> 'Black Peppercorn Grinder', 'unitOfMeasurement'=>'28 G', 'description'=>''],
							['itemID'=>245,'virtualItemID'=>'SDMM-00001',    'categoryID'=>47,'name'=> 'Organic Mayonnaise', 'unitOfMeasurement'=>'250 ML', 'description'=>''],
							['itemID'=>246,'virtualItemID'=>'SDMM-00002',    'categoryID'=>47,'name'=> 'English Mustard', 'unitOfMeasurement'=>'100 G', 'description'=>''],
							['itemID'=>247,'virtualItemID'=>'SDMM-00003',    'categoryID'=>47,'name'=> 'Wholegrain Mustard', 'unitOfMeasurement'=>'185 G', 'description'=>''],
							['itemID'=>248,'virtualItemID'=>'SDMM-00004',    'categoryID'=>47,'name'=> 'Light Reduced Cal Mayonnaise', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>249,'virtualItemID'=>'SDMM-00005',    'categoryID'=>47,'name'=> 'Miracle Whips', 'unitOfMeasurement'=>'30 OZ', 'description'=>''],
							['itemID'=>250,'virtualItemID'=>'SDMM-00006',    'categoryID'=>47,'name'=> 'Mayo Light Mayonnaise', 'unitOfMeasurement'=>'15 OZ', 'description'=>''],
							['itemID'=>251,'virtualItemID'=>'SDMM-00007',    'categoryID'=>47,'name'=> 'Mayonnaise', 'unitOfMeasurement'=>'15 OZ', 'description'=>''],
							['itemID'=>252,'virtualItemID'=>'SDMM-00008',    'categoryID'=>47,'name'=> 'Real Mayonnaise Dressing', 'unitOfMeasurement'=>'12 OZ', 'description'=>''],
							['itemID'=>253,'virtualItemID'=>'SDMM-00009',    'categoryID'=>47,'name'=> 'Light Mracle Whip', 'unitOfMeasurement'=>'15 OZ', 'description'=>''],
							['itemID'=>254,'virtualItemID'=>'SCPM-00001',    'categoryID'=>48,'name'=> 'Organic Fina Sea Salt', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>255,'virtualItemID'=>'SCPM-00002',    'categoryID'=>48,'name'=> 'Organic Coarse Sea Salt', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>256,'virtualItemID'=>'SCPM-00003',    'categoryID'=>48,'name'=> 'Organic Vegan Bouillon Powder', 'unitOfMeasurement'=>'150 G', 'description'=>''],
							['itemID'=>257,'virtualItemID'=>'SCPM-00004',    'categoryID'=>48,'name'=> 'Organic Flaky Sea Salt', 'unitOfMeasurement'=>'100 G', 'description'=>''],
							['itemID'=>258,'virtualItemID'=>'SCPM-00005',    'categoryID'=>48,'name'=> 'Cooking Salt', 'unitOfMeasurement'=>'454 G', 'description'=>''],
							['itemID'=>259,'virtualItemID'=>'SCPM-00006',    'categoryID'=>48,'name'=> 'Table Salt', 'unitOfMeasurement'=>'454 G', 'description'=>''],
							['itemID'=>260,'virtualItemID'=>'SCPM-00007',    'categoryID'=>48,'name'=> 'Reduced Sodium Sea Salt', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>261,'virtualItemID'=>'SCPM-00008',    'categoryID'=>48,'name'=> 'Sea Salt Flower', 'unitOfMeasurement'=>'250 G', 'description'=>''],
							['itemID'=>262,'virtualItemID'=>'SCPM-00009',    'categoryID'=>48,'name'=> 'Natural Sea Salt Coarse', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>263,'virtualItemID'=>'SGSW-00001',    'categoryID'=>49,'name'=> 'Organic Light Brown Sugar', 'unitOfMeasurement'=>'240 G', 'description'=>''],
							['itemID'=>264,'virtualItemID'=>'SGSW-00002',    'categoryID'=>49,'name'=> 'Coffee Sugar Sachet', 'unitOfMeasurement'=>'50 PCS', 'description'=>''],
							['itemID'=>265,'virtualItemID'=>'SGSW-00003',    'categoryID'=>49,'name'=> 'White Sugar Sachets', 'unitOfMeasurement'=>'50 PCS', 'description'=>''],
							['itemID'=>266,'virtualItemID'=>'SGSW-00004',    'categoryID'=>49,'name'=> 'White Sugar Sticks', 'unitOfMeasurement'=>'30 PCS', 'description'=>''],
							['itemID'=>267,'virtualItemID'=>'SGSW-00005',    'categoryID'=>49,'name'=> 'Golden Granulated Sugar Sticks', 'unitOfMeasurement'=>'30 PCS', 'description'=>''],
							['itemID'=>268,'virtualItemID'=>'SGSW-00006',    'categoryID'=>49,'name'=> 'Coffee Sugar', 'unitOfMeasurement'=>'908 G', 'description'=>''],
							['itemID'=>269,'virtualItemID'=>'SGSW-00007',    'categoryID'=>49,'name'=> 'Coffee Sugar', 'unitOfMeasurement'=>'380 G', 'description'=>''],
							['itemID'=>270,'virtualItemID'=>'SGSW-00008',    'categoryID'=>49,'name'=> 'Premium Coffee Sugar Crystals', 'unitOfMeasurement'=>'454 G', 'description'=>''],
							['itemID'=>271,'virtualItemID'=>'SGSW-00009',    'categoryID'=>49,'name'=> 'Raw Sugar Cube', 'unitOfMeasurement'=>'1 LB', 'description'=>''],
							['itemID'=>272,'virtualItemID'=>'SGSW-00010',    'categoryID'=>49,'name'=> 'Light Brown Sugar', 'unitOfMeasurement'=>'1 KG', 'description'=>''],
							['itemID'=>273,'virtualItemID'=>'SGSW-00011',    'categoryID'=>49,'name'=> 'Cube Sugar', 'unitOfMeasurement'=>'1 LB', 'description'=>''],
							['itemID'=>274,'virtualItemID'=>'SGSW-00012',    'categoryID'=>49,'name'=> 'Granulated Sugar', 'unitOfMeasurement'=>'2270 G', 'description'=>''],
							['itemID'=>275,'virtualItemID'=>'SGSW-00013',    'categoryID'=>49,'name'=> 'Granulated Sugar', 'unitOfMeasurement'=>'800 G', 'description'=>''],
							['itemID'=>276,'virtualItemID'=>'SGSW-00014',    'categoryID'=>49,'name'=> 'Granulated Sugar', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>277,'virtualItemID'=>'SGSW-00015',    'categoryID'=>49,'name'=> 'Coarse Granulated Sugar', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>278,'virtualItemID'=>'SGSW-00016',    'categoryID'=>49,'name'=> 'Rock Sugar', 'unitOfMeasurement'=>'350 G', 'description'=>''],
							['itemID'=>279,'virtualItemID'=>'SGSW-00017',    'categoryID'=>49,'name'=> 'Raw Sugar', 'unitOfMeasurement'=>'800 G', 'description'=>''],
							['itemID'=>280,'virtualItemID'=>'ASWN-00001',    'categoryID'=>53,'name'=> 'Kishu Nanko Umeshu', 'unitOfMeasurement'=>'720 ML', 'description'=>''],
							['itemID'=>281,'virtualItemID'=>'ASWN-00002',    'categoryID'=>53,'name'=> 'Kasen Sake Green Paper Pack', 'unitOfMeasurement'=>'2 L', 'description'=>''],
							['itemID'=>282,'virtualItemID'=>'ASWN-00003',    'categoryID'=>53,'name'=> 'Kome To Mizu No Sake', 'unitOfMeasurement'=>'720 ML', 'description'=>''],
							['itemID'=>283,'virtualItemID'=>'ASWN-00004',    'categoryID'=>53,'name'=> 'Horin Junmai Daiginjo', 'unitOfMeasurement'=>'720 ML', 'description'=>''],
							['itemID'=>284,'virtualItemID'=>'ASWN-00005',    'categoryID'=>53,'name'=> 'Yamada-Nishiki Tokubetsu Junmaishu', 'unitOfMeasurement'=>'300 ML', 'description'=>''],
							['itemID'=>285,'virtualItemID'=>'ASWN-00006',    'categoryID'=>53,'name'=> 'Sarari Yuzu', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>286,'virtualItemID'=>'ASWN-00007',    'categoryID'=>53,'name'=> 'Uji Green Tea Umeshu', 'unitOfMeasurement'=>'720 ML', 'description'=>''],
							['itemID'=>287,'virtualItemID'=>'ASWN-00008',    'categoryID'=>53,'name'=> 'The Black', 'unitOfMeasurement'=>'720 ML', 'description'=>''],
							['itemID'=>288,'virtualItemID'=>'ASWN-00009',    'categoryID'=>53,'name'=> 'Kokutomeshu', 'unitOfMeasurement'=>'720 ML', 'description'=>''],
							['itemID'=>289,'virtualItemID'=>'ASWN-00010',    'categoryID'=>53,'name'=> 'Non Sugar Natural Origianl', 'unitOfMeasurement'=>'650 ML', 'description'=>''],
							['itemID'=>290,'virtualItemID'=>'ASWN-00011',    'categoryID'=>53,'name'=> 'Classic Umeshu', 'unitOfMeasurement'=>'650 ML', 'description'=>''],
							['itemID'=>291,'virtualItemID'=>'ASWN-00012',    'categoryID'=>53,'name'=> 'Honey Umeshu', 'unitOfMeasurement'=>'650 ML', 'description'=>''],
							['itemID'=>292,'virtualItemID'=>'ASWN-00013',    'categoryID'=>53,'name'=> 'Classic Imeshu', 'unitOfMeasurement'=>'300 ML', 'description'=>''],
							['itemID'=>293,'virtualItemID'=>'ASWN-00014',    'categoryID'=>53,'name'=> 'Sake [L]', 'unitOfMeasurement'=>'1.8 L', 'description'=>''],
							['itemID'=>294,'virtualItemID'=>'ASWN-00015',    'categoryID'=>53,'name'=> 'Sake [M]', 'unitOfMeasurement'=>'720 ML', 'description'=>''],
							['itemID'=>295,'virtualItemID'=>'ASWN-00016',    'categoryID'=>53,'name'=> 'Sake [S]', 'unitOfMeasurement'=>'300 ML', 'description'=>''],
							['itemID'=>296,'virtualItemID'=>'ASWN-00017',    'categoryID'=>53,'name'=> 'Jyosen Blue Pack Sake', 'unitOfMeasurement'=>'2 L', 'description'=>''],
							['itemID'=>297,'virtualItemID'=>'ASWN-00018',    'categoryID'=>53,'name'=> 'Super Red Sake', 'unitOfMeasurement'=>'2 L', 'description'=>''],
							['itemID'=>298,'virtualItemID'=>'BSC-00001', 	  'categoryID'=>54,'name'=> 'Special Brew', 'unitOfMeasurement'=>'325 ML x 4', 'description'=>''],
							['itemID'=>299,'virtualItemID'=>'BSC-00002', 	  'categoryID'=>54,'name'=> 'Can Beer', 'unitOfMeasurement'=>'330 ML x 6', 'description'=>''],
							['itemID'=>300,'virtualItemID'=>'BSC-00003', 	  'categoryID'=>54,'name'=> 'King Can Beer', 'unitOfMeasurement'=>'500 ML x 4', 'description'=>''],
							['itemID'=>301,'virtualItemID'=>'BSC-00004', 	  'categoryID'=>54,'name'=> 'Beer Can', 'unitOfMeasurement'=>'330 ML x 12', 'description'=>''],
							['itemID'=>302,'virtualItemID'=>'BSC-00005', 	  'categoryID'=>54,'name'=> 'Supper Dry Beer Bot', 'unitOfMeasurement'=>'330 ML', 'description'=>''],
							['itemID'=>303,'virtualItemID'=>'BSC-00006', 	  'categoryID'=>54,'name'=> 'Tsing Tao Beer L Bot', 'unitOfMeasurement'=>'640 ML', 'description'=>''],
							['itemID'=>304,'virtualItemID'=>'BSC-00007', 	  'categoryID'=>54,'name'=> 'Premium Beer S Bot Tsing Tao', 'unitOfMeasurement'=>'296 ML', 'description'=>''],
							['itemID'=>305,'virtualItemID'=>'BWS-00001', 	  'categoryID'=>55,'name'=> 'Cordon Bleu Cognac [Qt.]', 'unitOfMeasurement'=>'70 CL', 'description'=>''],
							['itemID'=>306,'virtualItemID'=>'BWS-00002', 	  'categoryID'=>55,'name'=> 'Martell XO', 'unitOfMeasurement'=>'70 CL', 'description'=>''],
							['itemID'=>307,'virtualItemID'=>'BWS-00003', 	  'categoryID'=>55,'name'=> 'Noblige Cognac', 'unitOfMeasurement'=>'70 CL', 'description'=>''],
							['itemID'=>308,'virtualItemID'=>'BWS-00004', 	  'categoryID'=>55,'name'=> 'Hennessy XO', 'unitOfMeasurement'=>'70 CL', 'description'=>''],
							['itemID'=>309,'virtualItemID'=>'BWS-00005', 	  'categoryID'=>55,'name'=> 'Hennessy VSOP', 'unitOfMeasurement'=>'70 CL', 'description'=>''],
							['itemID'=>310,'virtualItemID'=>'BWS-00006', 	  'categoryID'=>55,'name'=> 'Johnnie Walker Black Label', 'unitOfMeasurement'=>'70 CL', 'description'=>''],
							['itemID'=>311,'virtualItemID'=>'BWS-00007', 	  'categoryID'=>55,'name'=> 'Johnnie Walker Red Label', 'unitOfMeasurement'=>'70 CL', 'description'=>''],
							['itemID'=>312,'virtualItemID'=>'BWS-00008', 	  'categoryID'=>55,'name'=> 'Johnnie Walker Gold Label Reserve', 'unitOfMeasurement'=>'700 ML', 'description'=>''],
							['itemID'=>313,'virtualItemID'=>'BWS-00009', 	  'categoryID'=>55,'name'=> 'Double Black Whisky', 'unitOfMeasurement'=>'700 ML', 'description'=>''],
							['itemID'=>314,'virtualItemID'=>'BWS-00010', 	  'categoryID'=>55,'name'=> '12 Year Old Whisky [Qt.]', 'unitOfMeasurement'=>'70 CL', 'description'=>''],
							['itemID'=>315,'virtualItemID'=>'BWS-00011', 	  'categoryID'=>55,'name'=> '18 yo Rare Whisky', 'unitOfMeasurement'=>'70 CL', 'description'=>''],
							['itemID'=>316,'virtualItemID'=>'CBDK-00001',	  'categoryID'=> 56,'name'=> 'Coca-Cola Zero', 'unitOfMeasurement'=>'300 ML x 12', 'description'=>''],
							['itemID'=>317,'virtualItemID'=>'CBDK-00002',	  'categoryID'=> 56,'name'=> 'Lemon-lime Flavoured Soda', 'unitOfMeasurement'=>'330 ML x 8', 'description'=>''],
							['itemID'=>318,'virtualItemID'=>'CBDK-00003',	  'categoryID'=> 56,'name'=> 'Cream Soda', 'unitOfMeasurement'=>'330 ML x 12', 'description'=>''],
							['itemID'=>319,'virtualItemID'=>'CBDK-00004',	  'categoryID'=> 56,'name'=> 'Cream Soda', 'unitOfMeasurement'=>'330 ML x 8', 'description'=>''],
							['itemID'=>320,'virtualItemID'=>'CBDK-00005',	  'categoryID'=> 56,'name'=> 'Zero Cream Soda', 'unitOfMeasurement'=>'330 ML x 8', 'description'=>''],
							['itemID'=>321,'virtualItemID'=>'CBDK-00006',	  'categoryID'=> 56,'name'=> 'Pepsi Cola', 'unitOfMeasurement'=>'330 ML x 8', 'description'=>''],
							['itemID'=>322,'virtualItemID'=>'CBDK-00007',	  'categoryID'=> 56,'name'=> '7 Up Free Carbonated Soft Drink', 'unitOfMeasurement'=>'330 ML x 8', 'description'=>''],
							['itemID'=>323,'virtualItemID'=>'CBDK-00008',	  'categoryID'=> 56,'name'=> '7 Up', 'unitOfMeasurement'=>'330 ML x 12', 'description'=>''],
							['itemID'=>324,'virtualItemID'=>'CBDK-00009',	  'categoryID'=> 56,'name'=> '7 Up', 'unitOfMeasurement'=>'330 ML x 8', 'description'=>''],
							['itemID'=>325,'virtualItemID'=>'CBDK-00010',	  'categoryID'=> 56,'name'=> '7 Up', 'unitOfMeasurement'=>'330 ML x 4', 'description'=>''],
							['itemID'=>326,'virtualItemID'=>'CBDK-00011',	  'categoryID'=> 56,'name'=> 'Coca-Cola', 'unitOfMeasurement'=>'330 ML x 8', 'description'=>''],
							['itemID'=>327,'virtualItemID'=>'CBDK-00012',	  'categoryID'=> 56,'name'=> 'Coca-Cola', 'unitOfMeasurement'=>'330 ML x 12', 'description'=>''],
							['itemID'=>328,'virtualItemID'=>'CBDK-00013',	  'categoryID'=> 56,'name'=> 'Orange Flavoured Soda Mini Can', 'unitOfMeasurement'=>'200 ML x 6', 'description'=>''],
							['itemID'=>329,'virtualItemID'=>'ENDK-00001',	  'categoryID'=> 57,'name'=> 'Ion Supply Drink', 'unitOfMeasurement'=>'340 ML x 6', 'description'=>''],
							['itemID'=>330,'virtualItemID'=>'ENDK-00002',	  'categoryID'=> 57,'name'=> 'Sweation Supply Ion Drink', 'unitOfMeasurement'=>'350 ML x 6', 'description'=>''],
							['itemID'=>331,'virtualItemID'=>'ENDK-00003',	  'categoryID'=> 57,'name'=> 'Lucozade Energy [Regular]', 'unitOfMeasurement'=>'300 ML x 4', 'description'=>''],
							['itemID'=>332,'virtualItemID'=>'ENDK-00004',	  'categoryID'=> 57,'name'=> 'Lucozade Energy [Orange]', 'unitOfMeasurement'=>'300 ML x 4', 'description'=>''],
							['itemID'=>333,'virtualItemID'=>'ENDK-00005',	  'categoryID'=> 57,'name'=> 'Lucozade Xtra', 'unitOfMeasurement'=>'300 ML x 4', 'description'=>''],
							['itemID'=>334,'virtualItemID'=>'ENDK-00006',	  'categoryID'=> 57,'name'=> 'Red Bull Energy Drink', 'unitOfMeasurement'=>'250 ML x 4', 'description'=>''],
							['itemID'=>335,'virtualItemID'=>'ENDK-00007',	  'categoryID'=> 57,'name'=> 'Red Bull Energy Drink [Sugar Free]', 'unitOfMeasurement'=>'250 ML x 4', 'description'=>''],
							['itemID'=>336,'virtualItemID'=>'JCCO-00001',	  'categoryID'=> 58,'name'=> '100% Organic Beetroot Juice', 'unitOfMeasurement'=>'750 ML', 'description'=>''],
							['itemID'=>337,'virtualItemID'=>'JCCO-00002',	  'categoryID'=> 58,'name'=> '100% Organic Ref Grape Juice', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>338,'virtualItemID'=>'JCCO-00003',	  'categoryID'=> 58,'name'=> 'Organic Prune Juice', 'unitOfMeasurement'=>'946 ML', 'description'=>''],
							['itemID'=>339,'virtualItemID'=>'JCCO-00004',	  'categoryID'=> 58,'name'=> 'Organic Pear Juice', 'unitOfMeasurement'=>'25 CL', 'description'=>''],
							['itemID'=>340,'virtualItemID'=>'JCCO-00005',	  'categoryID'=> 58,'name'=> 'Organic Carrot Juice - Pressed', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>341,'virtualItemID'=>'JCCO-00006',	  'categoryID'=> 58,'name'=> 'Organic Mango Nectar [35%]', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>342,'virtualItemID'=>'JCCO-00007',	  'categoryID'=> 58,'name'=> 'Organic Carrot & Apple Juice', 'unitOfMeasurement'=>'250 ML', 'description'=>''],
							['itemID'=>343,'virtualItemID'=>'JCCO-00008',	  'categoryID'=> 58,'name'=> 'Organic Apple Juice', 'unitOfMeasurement'=>'200 ML x 6', 'description'=>''],
							['itemID'=>344,'virtualItemID'=>'JCCO-00009',	  'categoryID'=> 58,'name'=> '100 Pure Coconut Water', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>345,'virtualItemID'=>'JCCO-00010',	  'categoryID'=> 58,'name'=> 'Coconut Water', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>346,'virtualItemID'=>'JCCO-00011',	  'categoryID'=> 58,'name'=> 'Coconut Watch with Pulp', 'unitOfMeasurement'=>'480 ML', 'description'=>''],
							['itemID'=>347,'virtualItemID'=>'JCCO-00012',	  'categoryID'=> 58,'name'=> 'Blackcurrant Drink', 'unitOfMeasurement'=>'450 ML', 'description'=>''],
							['itemID'=>348,'virtualItemID'=>'JCCO-00013',	  'categoryID'=> 58,'name'=> 'Orange Cordial', 'unitOfMeasurement'=>'840 ML', 'description'=>''],
							['itemID'=>349,'virtualItemID'=>'JCCO-00014',	  'categoryID'=> 58,'name'=> 'Lemon Cordial', 'unitOfMeasurement'=>'840 ML', 'description'=>''],
							['itemID'=>350,'virtualItemID'=>'JCCO-00015',	  'categoryID'=> 58,'name'=> 'Tomato Juice', 'unitOfMeasurement'=>'280 ML', 'description'=>''],
							['itemID'=>351,'virtualItemID'=>'MKYODK-00001',   'categoryID'=>59, 'name'=>'Organic Semi-skimmed Milk', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>352,'virtualItemID'=>'MKYODK-00002',   'categoryID'=>59, 'name'=>'Organic Rice Drink Original', 'unitOfMeasurement'=>'32 OZ', 'description'=>''],
							['itemID'=>353,'virtualItemID'=>'MKYODK-00003',   'categoryID'=>59, 'name'=>'Organic Rice Milk', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>354,'virtualItemID'=>'MKYODK-00004',   'categoryID'=>59, 'name'=>'Organic Plain Rice Drink', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>355,'virtualItemID'=>'MKYODK-00005',   'categoryID'=>59, 'name'=>'Organic Rice & Calcium Drink', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>356,'virtualItemID'=>'MKYODK-00006',   'categoryID'=>59, 'name'=>'Almond Rice Drink', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>357,'virtualItemID'=>'MKYODK-00007',   'categoryID'=>59, 'name'=>'Organic Rice Drink with Quinoa', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>358,'virtualItemID'=>'MKYODK-00008',   'categoryID'=>59, 'name'=>'Australia Rice Milk Unsweetened', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>359,'virtualItemID'=>'MKYODK-00009',   'categoryID'=>59, 'name'=>'Skim Uht Milk', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>360,'virtualItemID'=>'MKYODK-00010',   'categoryID'=>59, 'name'=>'Pauls skimmed Milk Uht Export', 'unitOfMeasurement'=>'1L', 'description'=>''],
							['itemID'=>361,'virtualItemID'=>'MKYODK-00011',   'categoryID'=>59, 'name'=>'Pauls Hcal Lf Milk Bev Uht Exp', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>362,'virtualItemID'=>'MKYODK-00012',   'categoryID'=>59, 'name'=>'Low Fat Milk Beverage Uht', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>363,'virtualItemID'=>'SODK-00001',     'categoryID'=>60, 'name'=>'Organicsoymilk Plus Plain', 'unitOfMeasurement'=>'32 OZ', 'description'=>''],
							['itemID'=>364,'virtualItemID'=>'SODK-00002',     'categoryID'=>60, 'name'=>'Organic Pure Soya Unsweetened', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>365,'virtualItemID'=>'SODK-00003',     'categoryID'=>60, 'name'=>'Organic Unswt Vanilla Soymilk', 'unitOfMeasurement'=>'32 OZ', 'description'=>''],
							['itemID'=>366,'virtualItemID'=>'SODK-00004',     'categoryID'=>60, 'name'=>'Organic Nature\'s Soy - Original', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>367,'virtualItemID'=>'SODK-00005',     'categoryID'=>60, 'name'=>'Australia Soy Milk Original', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>368,'virtualItemID'=>'SODK-00006',     'categoryID'=>60, 'name'=>'Australia Soy Milky', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>369,'virtualItemID'=>'SODK-00007',     'categoryID'=>60, 'name'=>'Vitasoy Soyabean Milk', 'unitOfMeasurement'=>'250 ML x 9', 'description'=>''],
							['itemID'=>370,'virtualItemID'=>'SODK-00008',     'categoryID'=>60, 'name'=>'Vitasoy Low Sugar Soya Bean Milk', 'unitOfMeasurement'=>'250 ML x 6', 'description'=>''],
							['itemID'=>371,'virtualItemID'=>'SODK-00009',     'categoryID'=>60, 'name'=>'Malted Soyabean Milk', 'unitOfMeasurement'=>'250 ML x 6', 'description'=>''],
							['itemID'=>372,'virtualItemID'=>'SODK-00010',     'categoryID'=>60, 'name'=>'Malted Soyabean Milk', 'unitOfMeasurement'=>'250 ML x 9', 'description'=>''],
							['itemID'=>373,'virtualItemID'=>'SODK-00011',     'categoryID'=>60, 'name'=>'Calci Plus Hi-Calcium Original Soya Drink', 'unitOfMeasurement'=>'250 ML x 6', 'description'=>''],
							['itemID'=>374,'virtualItemID'=>'SODK-00012',     'categoryID'=>60, 'name'=>'Calci Plus Hi-Calcium Original Soya Drink', 'unitOfMeasurement'=>'250 ML x 9', 'description'=>''],
							['itemID'=>375,'virtualItemID'=>'WT-00001',       'categoryID'=>61, 'name'=>'Watsons Distilled Water', 'unitOfMeasurement'=>'430 ML x 6', 'description'=>''],
							['itemID'=>376,'virtualItemID'=>'WT-00002',       'categoryID'=>61, 'name'=>'Distilled Water', 'unitOfMeasurement'=>'800 ML', 'description'=>''],
							['itemID'=>377,'virtualItemID'=>'WT-00003',       'categoryID'=>61, 'name'=>'Distilled Water', 'unitOfMeasurement'=>'1.25 L', 'description'=>''],
							['itemID'=>378,'virtualItemID'=>'WT-00004',       'categoryID'=>61, 'name'=>'Distilled Water with Minerals', 'unitOfMeasurement'=>'800 ML', 'description'=>''],
							['itemID'=>379,'virtualItemID'=>'WT-00005',       'categoryID'=>61, 'name'=>'Mineralised Water', 'unitOfMeasurement'=>'1.25 L', 'description'=>''],
							['itemID'=>380,'virtualItemID'=>'WT-00006',       'categoryID'=>61, 'name'=>'Mineral Water', 'unitOfMeasurement'=>'330 ML', 'description'=>''],
							['itemID'=>381,'virtualItemID'=>'WT-00007',       'categoryID'=>61, 'name'=>'Perrier Mint', 'unitOfMeasurement'=>'1 L', 'description'=>''],
							['itemID'=>382,'virtualItemID'=>'FHAPPE-00001',   'categoryID'=>66, 'name'=>'China Shandong Apple', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>383,'virtualItemID'=>'FHAPPE-00002',   'categoryID'=>66, 'name'=>'Small Gala Apple', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>384,'virtualItemID'=>'FHAPPE-00003',   'categoryID'=>66, 'name'=>'Envy Apple', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>385,'virtualItemID'=>'FHAPPE-00004',   'categoryID'=>66, 'name'=>'Granny Smith Apple', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>386,'virtualItemID'=>'FHAPPE-00005',   'categoryID'=>66, 'name'=>'Packham Pear', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>387,'virtualItemID'=>'FHAPPE-00006',   'categoryID'=>66, 'name'=>'Golden Pear', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>388,'virtualItemID'=>'FHAPPE-00007',   'categoryID'=>66, 'name'=>'Ya Pear', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>389,'virtualItemID'=>'FHAPPE-00008',   'categoryID'=>66, 'name'=>'Gong Pear [China]', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>390,'virtualItemID'=>'FHBANA-00001',   'categoryID'=>67, 'name'=>'Extra Sweet Banana [Philippine]', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>391,'virtualItemID'=>'FHBANA-00002',   'categoryID'=>67, 'name'=>'Banana', 'unitOfMeasurement'=>'1 LB', 'description'=>''],
							['itemID'=>392,'virtualItemID'=>'FHGPBR-00001',   'categoryID'=>68, 'name'=>'Organic Blueberry', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>393,'virtualItemID'=>'FHGPBR-00002',   'categoryID'=>68, 'name'=>'Blueberries', 'unitOfMeasurement'=>'125 G', 'description'=>''],
							['itemID'=>394,'virtualItemID'=>'FHGPBR-00003',   'categoryID'=>68, 'name'=>'Strawberries', 'unitOfMeasurement'=>'250 G', 'description'=>''],
							['itemID'=>395,'virtualItemID'=>'FHML-00001',      'categoryID'=>69,'name'=> 'Black Beauty Melon', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>396,'virtualItemID'=>'FHML-00002',      'categoryID'=>69,'name'=> 'Xi Zhou Mi Melon [China]', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>397,'virtualItemID'=>'FHBF-00001',      'categoryID'=>70,'name'=> 'Aust Chilled Grain Fed Beef Sirloin', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>398,'virtualItemID'=>'FHBF-00002',      'categoryID'=>70,'name'=> 'Aust Chilled Grain Fed Beef Rib Eye', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>399,'virtualItemID'=>'FHBF-00003',      'categoryID'=>70,'name'=> 'Aust Chilled Beef Oyster Balde Steak', 'unitOfMeasurement'=>'350 G', 'description'=>''],
							['itemID'=>400,'virtualItemID'=>'FHBF-00004',      'categoryID'=>70,'name'=> 'Aust Chilled Beef Striploin Steak', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>401,'virtualItemID'=>'FHBF-00005',      'categoryID'=>70,'name'=> 'Aust Chilled Beef Scotch Steak', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>402,'virtualItemID'=>'FHCT-00001',      'categoryID'=>71,'name'=> 'China Chilled Sesame Chicken', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>403,'virtualItemID'=>'FHMR-00001',      'categoryID'=>72,'name'=> 'Organic Crimini [Hong Kong]', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>404,'virtualItemID'=>'FHMR-00002',      'categoryID'=>72,'name'=> 'Taiwan Organic Pleurotus Mushroom', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>405,'virtualItemID'=>'FHMR-00003',      'categoryID'=>72,'name'=> 'BBQ Portobello Mushroom', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>406,'virtualItemID'=>'FHMR-00004',      'categoryID'=>72,'name'=> 'White Champignon', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>407,'virtualItemID'=>'FHMR-00005',      'categoryID'=>72,'name'=> 'Crimini', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>408,'virtualItemID'=>'FHMR-00006',      'categoryID'=>72,'name'=> 'Enoki Mushroom', 'unitOfMeasurement'=>'150 G', 'description'=>''],
							['itemID'=>409,'virtualItemID'=>'FHPT-00001',      'categoryID'=>73,'name'=> 'Potato', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>410,'virtualItemID'=>'FHPT-00002',      'categoryID'=>73,'name'=> 'Organic White Potato [Australia]', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>411,'virtualItemID'=>'FHRV-00001',      'categoryID'=>74,'name'=> 'Organic Baby Corn [Thailand]', 'unitOfMeasurement'=>'125 G', 'description'=>''],
							['itemID'=>412,'virtualItemID'=>'FHRV-00002',      'categoryID'=>74,'name'=> 'Organic Baby Carrot [USA]', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>413,'virtualItemID'=>'FHRV-00003',      'categoryID'=>74,'name'=> 'Baby Wong Bok', 'unitOfMeasurement'=>'450 G', 'description'=>''],
							['itemID'=>414,'virtualItemID'=>'FHRV-00004',      'categoryID'=>74,'name'=> 'Green Cabbage', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>415,'virtualItemID'=>'FHRV-00005',      'categoryID'=>74,'name'=> 'Wong Choi [China]', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>416,'virtualItemID'=>'FHRV-00006',      'categoryID'=>74,'name'=> 'Baby Asparagus', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>417,'virtualItemID'=>'FHRV-00007',      'categoryID'=>74,'name'=> 'Green Asparagus', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>418,'virtualItemID'=>'FHRV-00008',      'categoryID'=>74,'name'=> 'Sweet Corn [Australia]', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>419,'virtualItemID'=>'FHRV-00009',      'categoryID'=>74,'name'=> 'Long Bitter Cucumber', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>420,'virtualItemID'=>'FHRV-00010',      'categoryID'=>74,'name'=> 'Zucchini', 'unitOfMeasurement'=>'1 LB', 'description'=>''],
							['itemID'=>421,'virtualItemID'=>'FHRV-00011',      'categoryID'=>74,'name'=> 'Pumpkin [China]', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>422,'virtualItemID'=>'FHRV-00012',      'categoryID'=>74,'name'=> 'Sweet Bean', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>423,'virtualItemID'=>'FHRV-00013',      'categoryID'=>74,'name'=> 'Chinese Radish [China]', 'unitOfMeasurement'=>'1 LB', 'description'=>''],
							['itemID'=>424,'virtualItemID'=>'FHRV-00014',      'categoryID'=>74,'name'=> 'Organic Onion [Australia]', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>425,'virtualItemID'=>'FHSV-00001',      'categoryID'=>75,'name'=> 'Organic Yellow Capsicum', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>426,'virtualItemID'=>'FHSV-00002',      'categoryID'=>75,'name'=> 'Organic Red Capsicum', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>427,'virtualItemID'=>'FHSV-00003',      'categoryID'=>75,'name'=> 'Organic Green Capsicum', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>428,'virtualItemID'=>'FHSV-00004',      'categoryID'=>75,'name'=> 'Organic Tel Cucumber', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>429,'virtualItemID'=>'FHSV-00005',      'categoryID'=>75,'name'=> 'Butterhead Lettuce', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>430,'virtualItemID'=>'FHSV-00006',      'categoryID'=>75,'name'=> 'Iceburg Lettuce [China]', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>431,'virtualItemID'=>'FHSV-00007',      'categoryID'=>75,'name'=> 'Malaysia Tomato','unitOfMeasurement'=> '4 PCS', 'description'=>''],
							['itemID'=>432,'virtualItemID'=>'FHSV-00008',      'categoryID'=>75,'name'=> 'Malaysia Cherry Tomatoes', 'unitOfMeasurement'=>'350 G', 'description'=>''],
							['itemID'=>433,'virtualItemID'=>'FHSV-00009',      'categoryID'=>75,'name'=> 'Green Cucumber', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>434,'virtualItemID'=>'FHSP-00001',      'categoryID'=>76,'name'=> 'Garlic', 'unitOfMeasurement'=>'3 PCS', 'description'=>''],
							['itemID'=>435,'virtualItemID'=>'FHSP-00002',      'categoryID'=>76,'name'=> 'Coriander [China]', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>436,'virtualItemID'=>'FHSP-00003',      'categoryID'=>76,'name'=> 'Lemon Grass [Thailand]', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>437,'virtualItemID'=>'FHSP-00004',      'categoryID'=>76,'name'=> 'Spring Onions [China]', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>438,'virtualItemID'=>'FHSP-00005',      'categoryID'=>76,'name'=> 'Ginger', 'unitOfMeasurement'=>'340 G', 'description'=>''],
							['itemID'=>439,'virtualItemID'=>'FHSP-00006',      'categoryID'=>76,'name'=> 'Red Hot Pepper [Thailand]', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>440,'virtualItemID'=>'FHOTH-00001',     'categoryID'=> 77,'name'=> 'Organic Soya Bean Sprout', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>441,'virtualItemID'=>'FHOTH-00002',     'categoryID'=> 77,'name'=> 'Organic Bean Sprout [HK]', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>442,'virtualItemID'=>'FHOTH-00003',     'categoryID'=> 77,'name'=> 'Broccoli', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>443,'virtualItemID'=>'FHOTH-00004',     'categoryID'=> 77,'name'=> 'Cauliflower', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>444,'virtualItemID'=>'FHOTH-00005',     'categoryID'=> 77,'name'=> 'Eggplant [China]', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>445,'virtualItemID'=>'FZFH-00001',      'categoryID'=>82, 'name'=>'Frozen Atlantic Salmon Steak', 'unitOfMeasurement'=>'2 PCS', 'description'=>''],
							['itemID'=>446,'virtualItemID'=>'FZFH-00002',      'categoryID'=>82, 'name'=>'Frozen Greenland Halibut Steaks', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>447,'virtualItemID'=>'FZFH-00003',      'categoryID'=>82, 'name'=>'Frozen Yellow Coraker', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>448,'virtualItemID'=>'FZFH-00004',      'categoryID'=>82, 'name'=>'Frozen Capelin [Fish]', 'unitOfMeasurement'=>'8 PCS', 'description'=>''],
							['itemID'=>449,'virtualItemID'=>'FZFH-00005',      'categoryID'=>82, 'name'=>'Frozen Pacific Saury [Fish]', 'unitOfMeasurement'=>'3 PCS', 'description'=>''],
							['itemID'=>450,'virtualItemID'=>'FZFH-00006',      'categoryID'=>82, 'name'=>'Frozen Atlantic Salmon Head [Half Cut]', 'unitOfMeasurement'=>'2 PCS', 'description'=>''],
							['itemID'=>451,'virtualItemID'=>'FZFH-00007',      'categoryID'=>82, 'name'=>'Frozen Chinese Noodle Fish', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>452,'virtualItemID'=>'FZFH-00008',      'categoryID'=>82, 'name'=>'Golden Pompano', 'unitOfMeasurement'=>'350 G', 'description'=>''],
							['itemID'=>453,'virtualItemID'=>'FZFH-00009',      'categoryID'=>82, 'name'=>'Frozen Miyazaki Yellow Tail Collar', 'unitOfMeasurement'=>'10 PCS', 'description'=>''],
							['itemID'=>454,'virtualItemID'=>'FZFH-00010',      'categoryID'=>82, 'name'=>'Frozen Atlentic Salmon Back Bones', 'unitOfMeasurement'=>'550 G', 'description'=>''],
							['itemID'=>455,'virtualItemID'=>'FZFFCSOTH-00001', 'categoryID'=>83, 'name'=>'Frozen Mackerel Fillet [Fish]', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>456,'virtualItemID'=>'FZFFCSOTH-00002', 'categoryID'=>83, 'name'=>'Frozen Striped Catfish', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>457,'virtualItemID'=>'FZFFCSOTH-00003', 'categoryID'=>83, 'name'=>'Frozen Skin On Atlantic Salmon Fillet', 'unitOfMeasurement'=>'240 G', 'description'=>''],
							['itemID'=>458,'virtualItemID'=>'FZFFCSOTH-00004', 'categoryID'=>83, 'name'=>'Imitation Brab Stick', 'unitOfMeasurement'=>'250 G', 'description'=>''],
							['itemID'=>459,'virtualItemID'=>'FZFFCSOTH-00005', 'categoryID'=>83, 'name'=>'Cod Fish Finger', 'unitOfMeasurement'=>'280 G', 'description'=>''],
							['itemID'=>460,'virtualItemID'=>'FZFFCSOTH-00006', 'categoryID'=>83, 'name'=>'Crispy Fish Fingers', 'unitOfMeasurement'=>'224 G', 'description'=>''],
							['itemID'=>461,'virtualItemID'=>'FZFFCSOTH-00007', 'categoryID'=>83, 'name'=>'Crab Stick', 'unitOfMeasurement'=>'125 G', 'description'=>''],
							['itemID'=>462,'virtualItemID'=>'FZPCOTHSEA-00001', 'categoryID'=>84,'name'=> 'Frozen Korea Oyster', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>463,'virtualItemID'=>'FZPCOTHSEA-00002', 'categoryID'=>84,'name'=> 'Frozen Canadian Wild Whole Cooked Lobster', 'unitOfMeasurement'=>'1 PC', 'description'=>''],
							['itemID'=>464,'virtualItemID'=>'FZPCOTHSEA-00003', 'categoryID'=>84,'name'=> 'Frozen Bay Scallop', 'unitOfMeasurement'=>'227 G', 'description'=>''],
							['itemID'=>465,'virtualItemID'=>'FZPCOTHSEA-00004', 'categoryID'=>84,'name'=> 'Frozen Yesso Scallop Meat', 'unitOfMeasurement'=>'450 G', 'description'=>''],
							['itemID'=>466,'virtualItemID'=>'FZPCOTHSEA-00005', 'categoryID'=>84,'name'=> 'Frozen Yesso Scallop Meat', 'unitOfMeasurement'=>'255 G', 'description'=>''],
							['itemID'=>467,'virtualItemID'=>'FZPCOTHSEA-00006', 'categoryID'=>84,'name'=> 'Frozen White Shrimp [Wild Catch]', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>468,'virtualItemID'=>'FZPCOTHSEA-00007', 'categoryID'=>84,'name'=> 'Frozed Whiteleg Shrimp Meat', 'unitOfMeasurement'=>'180 G', 'description'=>''],
							['itemID'=>469,'virtualItemID'=>'FZPCOTHSEA-00008', 'categoryID'=>84,'name'=> 'Frozen Flower Prawn', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>470,'virtualItemID'=>'FZPCOTHSEA-00009', 'categoryID'=>84,'name'=> 'Frozen Whole Black Tiger Prawn', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>471,'virtualItemID'=>'FZBF-00001',       'categoryID'=>85,'name'=> 'Select OX Tail', 'unitOfMeasurement'=>'454 G', 'description'=>''],
							['itemID'=>472,'virtualItemID'=>'FZBF-00002',       'categoryID'=>85,'name'=> 'Canada Beef Short Ribs', 'unitOfMeasurement'=>'1 LB', 'description'=>''],
							['itemID'=>473,'virtualItemID'=>'FZBF-00003',       'categoryID'=>85,'name'=> 'Frozen UK Beef Short Rib', 'unitOfMeasurement'=>'454 G', 'description'=>''],
							['itemID'=>474,'virtualItemID'=>'FZBF-00004',       'categoryID'=>85,'name'=> 'US Frozen Beef Diced', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>475,'virtualItemID'=>'FZBF-00005',       'categoryID'=>85,'name'=> 'US Beef Rib Finger', 'unitOfMeasurement'=>'454 G', 'description'=>''],
							['itemID'=>476,'virtualItemID'=>'FZBF-00006',       'categoryID'=>85,'name'=> 'US Grain Fed Hot Pot Beef', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>477,'virtualItemID'=>'FZLB-00001',       'categoryID'=>86,'name'=> 'NZ Lamb Shoulder B/L Sliced', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>478,'virtualItemID'=>'FZPK-00001',       'categoryID'=>87,'name'=> 'Danish Organic Pork Collar Chop', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>479,'virtualItemID'=>'FZPK-00002',       'categoryID'=>87,'name'=> 'Danish Organic Boneless Pork Chop', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>480,'virtualItemID'=>'FZPK-00003',       'categoryID'=>87,'name'=> 'Salted Pork Knuckle', 'unitOfMeasurement'=>'800 G', 'description'=>''],
							['itemID'=>481,'virtualItemID'=>'FZPK-00004',       'categoryID'=>87,'name'=> 'Danish Pork Belly Steak', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>482,'virtualItemID'=>'FZPK-00005',       'categoryID'=>87,'name'=> 'Danish Boneless Pork Tenderloin Steak', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>483,'virtualItemID'=>'FZPK-00006',       'categoryID'=>87,'name'=> 'Danish Boneless Pork Chop', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>484,'virtualItemID'=>'FZPK-00007',       'categoryID'=>87,'name'=> 'Danish Pork Sparerib Dice', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>485,'virtualItemID'=>'FZPK-00008',       'categoryID'=>87,'name'=> 'Danish Pork Boneless Collar Chop', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>486,'virtualItemID'=>'FZPK-00009',       'categoryID'=>87,'name'=> 'Danish Pork Tenderloin', 'unitOfMeasurement'=>'450 G', 'description'=>''],
							['itemID'=>487,'virtualItemID'=>'FZPK-00010',       'categoryID'=>87,'name'=> 'Spain Chestnut-Fed Pork Belly', 'unitOfMeasurement'=>'180 G', 'description'=>''],
							['itemID'=>488,'virtualItemID'=>'FZPK-00011',       'categoryID'=>87,'name'=> 'Spain Chestnut-Fed Pork Collar', 'unitOfMeasurement'=>'200 G', 'description'=>''],
							['itemID'=>489,'virtualItemID'=>'FZPO-00001',       'categoryID'=>88,'name'=> 'USA Organic Chicken Breast Boneless Skin', 'unitOfMeasurement'=>'1.5 LB', 'description'=>''],
							['itemID'=>490,'virtualItemID'=>'FZPO-00002',       'categoryID'=>88,'name'=> 'USA Organic Chicken Party Wing', 'unitOfMeasurement'=>'1.5 LB', 'description'=>''],
							['itemID'=>491,'virtualItemID'=>'FZPO-00003',       'categoryID'=>88,'name'=> 'USA Organic Chicken Drumstick', 'unitOfMeasurement'=>'1.5 LB', 'description'=>''],
							['itemID'=>492,'virtualItemID'=>'FZPO-00004',       'categoryID'=>88,'name'=> 'USA Organic Chicken Tenderloin', 'unitOfMeasurement'=>'1.5 LB', 'description'=>''],
							['itemID'=>493,'virtualItemID'=>'FZPO-00005',       'categoryID'=>88,'name'=> 'Select Brazilian Mid Joint Wing', 'unitOfMeasurement'=>'2 LB', 'description'=>''],
							['itemID'=>494,'virtualItemID'=>'FZPO-00006',       'categoryID'=>88,'name'=> 'Frozen Chicken Tenderloins', 'unitOfMeasurement'=>'1.5 LB', 'description'=>''],
							['itemID'=>495,'virtualItemID'=>'FZPO-00007',       'categoryID'=>88,'name'=> 'Select Boneless Chicken Thighs', 'unitOfMeasurement'=>'1 Pack', 'description'=>''],
							['itemID'=>496,'virtualItemID'=>'FZPO-00008',       'categoryID'=>88,'name'=> 'Frozen US Chix Mid Joint Wing', 'unitOfMeasurement'=>'2 LB', 'description'=>''],
							['itemID'=>497,'virtualItemID'=>'FZSBBM-00001',     'categoryID'=>89,'name'=> 'Frankfurter Sausages', 'unitOfMeasurement'=>'300 G', 'description'=>''],
							['itemID'=>498,'virtualItemID'=>'FZSBBM-00002',     'categoryID'=>89,'name'=> 'Cocktail Sausage - Honey Flavour', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>499,'virtualItemID'=>'FZSBBM-00003',     'categoryID'=>89,'name'=> 'Cocktail Sausage - Cheese Flavour', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>500,'virtualItemID'=>'FZSBBM-00004',     'categoryID'=>89,'name'=> 'Chicken Frank', 'unitOfMeasurement'=>'12 OZ', 'description'=>''],
							['itemID'=>501,'virtualItemID'=>'FZSBBM-00005',     'categoryID'=>89,'name'=> 'Cheese Crispy Sausage', 'unitOfMeasurement'=>'1 LB', 'description'=>''],
							['itemID'=>502,'virtualItemID'=>'FZSBBM-00006',     'categoryID'=>89,'name'=> 'Honey Crispy Sausage', 'unitOfMeasurement'=>'1 LB', 'description'=>''],
							['itemID'=>503,'virtualItemID'=>'FZSBBM-00007',     'categoryID'=>89,'name'=> 'Pork Patties', 'unitOfMeasurement'=>'170 G', 'description'=>''],
							['itemID'=>504,'virtualItemID'=>'FZSBBM-00008',     'categoryID'=>89,'name'=> 'Chicken Franks', 'unitOfMeasurement'=>'340 G', 'description'=>''],
							['itemID'=>505,'virtualItemID'=>'FZSBBM-00009',     'categoryID'=>89,'name'=> 'Pork Patties', 'unitOfMeasurement'=>'6 OZ', 'description'=>''],
							['itemID'=>506,'virtualItemID'=>'FZSBBM-00010',     'categoryID'=>89,'name'=> 'Grillsausages with Cheddar Cheese', 'unitOfMeasurement'=>'400 G', 'description'=>''],
							['itemID'=>507,'virtualItemID'=>'FZBP-00001',       'categoryID'=>90,'name'=> 'Garden Peas', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>508,'virtualItemID'=>'FZBP-00002',       'categoryID'=>90,'name'=> 'Petit Pois', 'unitOfMeasurement'=>'450 G', 'description'=>''],
							['itemID'=>509,'virtualItemID'=>'FZBP-00003',       'categoryID'=>90,'name'=> 'Vegan Ultimate Beefless Burger', 'unitOfMeasurement'=>'12 OZ', 'description'=>''],
							['itemID'=>510,'virtualItemID'=>'FZBP-00004',       'categoryID'=>90,'name'=> 'Peas Garden', 'unitOfMeasurement'=>'450 G', 'description'=>''],
							['itemID'=>511,'virtualItemID'=>'FZCN-00001',       'categoryID'=>91,'name'=> 'Sweet Corn', 'unitOfMeasurement'=>'500 G', 'description'=>''],
							['itemID'=>512,'virtualItemID'=>'FZFT-00001',       'categoryID'=>92,'name'=> 'Triple Berry Blend', 'unitOfMeasurement'=>'16 OZ', 'description'=>''],
							['itemID'=>513,'virtualItemID'=>'FZFT-00002',       'categoryID'=>92,'name'=> 'Spectrum Blend', 'unitOfMeasurement'=>'16 OZ', 'description'=>''],
							['itemID'=>514,'virtualItemID'=>'FZPT-00001',       'categoryID'=>93,'name'=> 'Hash Brown Potato Patties', 'unitOfMeasurement'=>'600 G', 'description'=>''],
							['itemID'=>515,'virtualItemID'=>'FZPT-00002',       'categoryID'=>93,'name'=> 'Hash Brown Onion', 'unitOfMeasurement'=>'600 G', 'description'=>''],
							['itemID'=>516,'virtualItemID'=>'FZPT-00003',       'categoryID'=>93,'name'=> 'Crinkle Cut French Fries', 'unitOfMeasurement'=>'1 KG', 'description'=>''],
							['itemID'=>517,'virtualItemID'=>'FZPT-00004',       'categoryID'=>93,'name'=> 'Fried Potatoes Country Cut', 'unitOfMeasurement'=>'1 KG', 'description'=>''],
							['itemID'=>518,'virtualItemID'=>'FZPT-00005',       'categoryID'=>93,'name'=> 'Shoestring French Fried Potato', 'unitOfMeasurement'=>'1 KG', 'description'=>''],
							['itemID'=>519,'virtualItemID'=>'FZPT-00006',       'categoryID'=>93,'name'=> 'Homestyle Potato Strips', 'unitOfMeasurement'=>'750 G', 'description'=>''],
							['itemID'=>520,'virtualItemID'=>'Test-00007',       'categoryID'=>93,'name'=> 'Goldkiwi', 'unitOfMeasurement'=>'10 G', 'description'=>'test warehouse'],
							['itemID'=>521,'virtualItemID'=>'Test-00008',       'categoryID'=>93,'name'=> 'Goldapple', 'unitOfMeasurement'=>'10 G', 'description'=>'test SPO'],
							['itemID'=>522,'virtualItemID'=>'Test-00009',       'categoryID'=>93,'name'=> 'Goldbanana', 'unitOfMeasurement'=>'10 G', 'description'=>'test 2BPA']
							);
		
		for($i=0; $i<count($collection); $i++) {
			//for debug input data error
			//print_r(Arr::get($collection,$i));
			DB::table('item')->insert([Arr::get($collection,$i)]);
		}
    }
}
